wso2/testgrid

reporting/src/main/java/org/wso2/carbon/testgrid/reporting/TestReportEngine.java, reporting/src/main/java/org/wso2/carbon/testgrid/reporting/beans/JmeterTestResult.java, reporting/src/main/java/org/wso2/carbon/testgrid/reporting/beans/TestResult.java, reporting/src/main/java/org/wso2/carbon/testgrid/reporting/beans/TestResultBeanFactory.java, reporting/src/main/java/org/wso2/carbon/testgrid/reporting/reader/CSVResultReader.java, reporting/src/main/java/org/wso2/carbon/testgrid/reporting/reader/ResultReader.java, reporting/src/main/java/org/wso2/carbon/testgrid/reporting/util/FileUtil.java, reporting/src/test/java/org/wso2/carbon/testgrid/reporting/TestReportEngineTest.java, reporting/src/test/java/org/wso2/carbon/testgrid/reporting/reader/CSVResultReaderTest.java
Resolves #10 
A single report will be generated for multiple test results output
When a test plan is triggered, for each test scenario multiple outputs will be produced. A report is required to be generated for each test scenario.
* Fix produce only a single report for a test scenario output
=> Fix report engine to output reports for multiple files

common/src/main/java/org/wso2/carbon/testgrid/common/InfrastructureProvider.java, common/src/main/java/org/wso2/carbon/testgrid/common/Script.java, common/src/main/java/org/wso2/carbon/testgrid/common/TestPlan.java, core/src/main/java/org/wso2/carbon/testgrid/core/ScenarioExecutor.java, core/src/main/resources/testplan1.yaml, core/src/main/resources/two-node.yaml, infrastructure/pom.xml, infrastructure/src/main/java/org/wso2/carbon/testgrid/infrastructure/InfrastructureProviderFactory.java, infrastructure/src/main/java/org/wso2/carbon/testgrid/infrastructure/InfrastructureProviderServiceImpl.java, infrastructure/src/main/java/org/wso2/carbon/testgrid/infrastructure/providers/OpenStackProvider.java, reporting/src/main/java/org/wso2/carbon/testgrid/reporting/TestReportEngineImpl.java, reporting/src/test/java/org/wso2/carbon/testgrid/reporting/TestReportEngineTest.java
This adds the functionality to accommodate shell script execution into the TestGrid Infrastructure module.
Resolves #43.
To have Shell script execution as an infrastructure provider
Included a canHandle method to be implemented by the InfrastructureProviders, so that the InfrastructureProviderFactory can get the supported implementation by invoking it.
=> Updated InfrastructureProvider to support script execution

common/src/main/java/org/wso2/carbon/testgrid/common/DeployerService.java, common/src/main/java/org/wso2/carbon/testgrid/common/Deployment.java, common/src/main/java/org/wso2/carbon/testgrid/common/constants/TestGridConstants.java, core/src/main/java/org/wso2/carbon/testgrid/core/TestPlanExecutor.java, core/src/test/java/org/wso2/carbon/testgrid/core/TestGridMgtServiceTest.java
> Resolve #69 
> This will enable implementations of DeployerService to fetch all necessary details from the Deployment object.
> Updated Deployment object to hold the required parameters.
=> Change DeployerService interface to accept Deployment object

core/src/test/java/org/wso2/testgrid/core/ScenarioExecutorTest.java, core/src/test/java/org/wso2/testgrid/core/TestGridMgtServiceTest.java
Resolves #94
This affected in `powermock` versions 1.6.0+ and Java 1.7_25+
* Fix java.lang.LinkageError when running tests in testgrid core
* Fixed java.lang.LinkageError when running tests in testgrid core
- Unit tests 
> N/A - Fixing build exception when running tests
> N/A - Fixing build exception when running tests
=> Fix java.lang.LinkageError in testgrid core

core/pom.xml, core/src/main/java/org/wso2/testgrid/core/Main.java, core/src/main/java/org/wso2/testgrid/core/TestGridUtil.java, core/src/main/java/org/wso2/testgrid/core/command/Command.java, core/src/main/java/org/wso2/testgrid/core/command/CommandHandler.java, core/src/main/java/org/wso2/testgrid/core/command/CreateProductTestPlanCommand.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateReportCommand.java, core/src/main/java/org/wso2/testgrid/core/command/HelpCommand.java, core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java, distribution/bin/log4j2.xml, pom.xml
Resolves #101 
Provides separate command options to execute creation of product test plan, running each test plan, and generating reports.
Each testplan should be able to run concurrently for a given product, version, and channel. With current design, this is not possible. This PR introduces separate commands to execute each of these options.
=> Resolves wso2-testgrid/101: separate execution command options.

common/src/main/java/org/wso2/testgrid/common/Database.java, common/src/main/java/org/wso2/testgrid/common/InfraCombination.java, common/src/main/java/org/wso2/testgrid/common/InfraResult.java, common/src/main/java/org/wso2/testgrid/common/OperatingSystem.java, common/src/main/java/org/wso2/testgrid/common/ProductTestPlan.java, common/src/main/java/org/wso2/testgrid/common/TestCase.java, common/src/main/java/org/wso2/testgrid/common/TestPlan.java, common/src/main/java/org/wso2/testgrid/common/TestScenario.java, common/src/main/java/org/wso2/testgrid/common/util/StringUtil.java, core/src/test/java/org/wso2/testgrid/core/TestGridMgtServiceTest.java
Resolves #151, #152
* Fix null pointer exceptions in `toString()` methods in the entities
* Fix table id column referenced instead of the entity field name when handling database transactions with mappings.
* Fix null pointer exceptions in `toString()` methods in the entities
* Fix table id column referenced instead of the entity field name when handling database transactions with mappings.
=> Fix errors in DB entity classes

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/aws/AWSManager.java
Removing the unused import that caused the build to fail.
resolves #234
=> Fix unused import checkstyle error

core/src/main/java/org/wso2/testgrid/core/command/CreateProductCommand.java, dao/src/main/java/org/wso2/testgrid/dao/uow/ProductUOW.java
Implemented command to persist "Product" in DB
Resolves #245
* Implement command to persist "Product" in DB
=> Implement command to persist "Product" in DB

automation/pom.xml, common/pom.xml, core/pom.xml, dao/pom.xml, deployment/pom.xml, infrastructure/pom.xml, pom.xml, reporting/pom.xml, test/coverage/pom.xml, web/pom.xml
Resolves #48 
Jacoco test coverage report generation implemented
Generate test coverage report for TestGrid during build
* Add Jacoco test coverage report generation
- Unit tests 
> N/A - Test coverage report generation
> N/A - Test coverage report generation
=> Add jacoco test coverage generation on build

test/coverage/pom.xml
Fix build failure due to no parent.relativePath
This PR is fixing a build issue in PR #289 
- Unit tests 
> N/A
> N/A
=> Fix build failure due to no parent.relativePath

distribution/bin/log4j2.xml
Please note that this PR is dependant on PR https://github.com/wso2-incubator/testgrid/pull/307
Correct the log file path and name.
Resolves #323 
* Incorrect log file path and location in Jenkins environment corrected.
=> Fix incorrect log file path and name in Jenkins environment 

web/src/main/react-dashboard/src/App.js, web/src/main/react-dashboard/src/components/TestCaseView.js
Resolves #330 
Change style of dashboard table to show the complete content of error message.
Used CSS property `wordWrap:break-word`
=> Fix dashboard error message display restrictions 

core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java, distribution/bin/log4j2.xml
Fixes logs related to testing execution not stored in the correct file path with the correct file name.
Resolves #323
* Fixed logs related to testing execution not stored in the correct file path with the correct file name.
=> Fix logs related to test execution is not persisted in the correct location

jenkins-pipelines/Jenkinsfile
Archive test run reports and logs in AWS S3 for traceability.
Resolves #302
* Archive test run logs and reports in AWS S3
Test run reports and logs need to be archived in the cloud. The archived reports and logs will be against for each deployment pattern and infrastruncture combination. This would help to trace test failures for any deployment pattern and infrastructure combination for any given time.
- Unit tests 
> N/A
> N/A
=> Archive test run logs and reports in AWS S3

distribution/bin/log4j2.xml
Add date pattern to rolling files in log4j.xml
Resolves #380
=> Fix RollingFileAppender missing date pattern error

core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java, jenkins-pipelines/Jenkinsfile, reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngine.java
* Delete log and report files via the Jenkins pipeline script
* Test report generation for each test plan removed 
* Test report for the product will be stored in the directory for the relevant product
Resolves #377 
* Remove test run logs and reports from Jenkins after archiving 
=> Remove test run logs and reports from Jenkins after archiving 

common/src/main/java/org/wso2/testgrid/common/TestGridConstants.java, common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java, core/src/main/java/org/wso2/testgrid/core/Main.java, core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java, reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngine.java
We shouldn't just fail if the TESTGRID_HOME env var is not found. Instead, we should default to an appropriate location such as ~/.testgrid.
Resolves #393
Better user experience
Defaults to ~/.testgrid
N/A
N/A
Default testgrid_home is set to ~/.testgrid.
N/A
N/A
N/A
N/A
=> TESTGRID_HOME should default to ~/.testgrid if the env variable is not found

web/pom.xml, web/src/main/react-dashboard/package.json, web/src/main/react-dashboard/src/App.js, web/src/main/react-dashboard/src/components/DeploymentPatternView.js, web/src/main/react-dashboard/src/components/InfraCombinationView.js, web/src/main/react-dashboard/src/components/ProductStatusView.js, web/src/main/react-dashboard/src/components/TestRunView.js
Resolves #403 
Removed version from dashboard URL
Use `##` notation to hide the version of war file from dashboard URL and change the 
base URL as `/testgrid/dashboard/`
> #405
=> Change dashboard base URL

deployment/src/main/java/org/wso2/testgrid/deployment/deployers/ShellDeployer.java
This PR Update ShellDeployer to use TestGridUtil method to get the TESTGRID_HOME location.
Resolves #415
=> Update ShellDeployer to use TestgridUtil method to get TESTGRID_HOME

common/src/main/java/org/wso2/testgrid/common/TestGridError.java, common/src/main/java/org/wso2/testgrid/common/infrastructure/IncompatibleInfrastructureParameterException.java, common/src/main/java/org/wso2/testgrid/common/infrastructure/InfrastructureCombination.java, common/src/main/java/org/wso2/testgrid/common/infrastructure/InfrastructureParameter.java, common/src/main/java/org/wso2/testgrid/common/infrastructure/InfrastructureValueSet.java, common/src/main/java/org/wso2/testgrid/common/infrastructure/package-info.java, core/src/main/java/org/wso2/testgrid/core/TestConfig.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java, core/src/main/java/org/wso2/testgrid/infrastructure/InfrastructureCombinationsProvider.java, core/src/test/java/org/wso2/testgrid/infrastructure/InfrastructureCombinationsProviderTest.java, core/src/test/resources/testng.xml, dao/pom.xml, dao/src/main/java/org/wso2/testgrid/dao/repository/InfrastructureParameterRepository.java, dao/src/main/java/org/wso2/testgrid/dao/specification/Specification.java, dao/src/main/java/org/wso2/testgrid/dao/uow/InfrastructureParameterUOW.java, dao/src/main/resources/META-INF/persistence.xml, dao/src/test/resources/META-INF/persistence.xml
The values of each infrastructure value-set is maintained platform-wide in a single spreadsheet. Product teams are not given the authority to select the infrastructure. If a given product cannot support a given infrastructure, then that needs to be escalated, and if valid, an exclusion-clause can be added to the spreadsheet.
Resolves #343 
Single location to manage all infrastructure combinations.
* Introduced a new table - InfrastructureParameter
* The InfrastructureParameterRepository then reads the data from the database and provide domain-level InfrastructureValueSet objects for each infrastructure type.
* Then, the InfrastructureCombinationsProvider generates the InfrastructureCombination set by reading the value-sets.
N/A
Generate infrastructure combinations via value-sets in a …
=> Generate infrastructure combinations via value-sets in a database.

common/src/main/java/org/wso2/testgrid/common/TestGridConstants.java, common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java, core/src/main/java/org/wso2/testgrid/core/Main.java, distribution/bin/log4j2.xml, distribution/bin/testgrid, logging/src/main/java/org/wso2/testgrid/logging/plugins/LogFilePathLookup.java, web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java, web/src/main/java/org/wso2/testgrid/web/utils/ConfigurationContext.java, web/src/main/java/org/wso2/testgrid/web/utils/Constants.java
Set the TESTGRID_HOME within shell script itself. Enforcing the default testgrid.home as the logging directory for log4j.
Resolves #435 
Resolves #414 
Set testgrid.home system property within the shell script itself. The log4j2.xml will read this system property to know the log file path.
N/A
=> Set the TESTGRID_HOME within shell script itself.

distribution/bin/log4j2.xml
Logging only the warn logs of org.eclipse.persistence into stdout
since its logs are too verbose. The info logs are sent to the testgrid.log. Fixes #408
better readability.
via log4j2.xml
N/A
=> Logging only the warn logs of org.eclipse.persistence into stdout

common/src/main/java/org/wso2/testgrid/common/infrastructure/InfrastructureParameter.java
Support DBEngine, DBEngineVersion as infrastructure parameters.
Backward-compatibility.
Support DBEngine, DBEngineVersion as infrastructure parameters.
#343
=> Support DBEngine, DBEngineVersion as infrastructure parameters.

web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java, web/src/main/java/org/wso2/testgrid/web/plugins/AWSArtifactReader.java
> Adds changes to provide missing AWS credentials causing inability to download the log file from the dashboard.
> Resolves #410 
> Partially resolves #409
> Enable downloading the log file from the dashboard
> AWS credentials were fetched from environment variables. This has been changed to read the credentials from a property file using the AWS PropertiesFileCredentialsProvider.
> Fixed log file download link in dashboard
=> Modify AWSArtifactReader to get AWS credentials from properties file

automation/src/test/java/org/wso2/testgrid/automation/executor/JMeterExecutorTest.java, common/src/main/java/org/wso2/testgrid/common/util/FileUtil.java
Resolves #427 
Fix the code violations 
Instead of manually closing the input stream, use 'try-with-resource' method.
=> Fix coding standard violations

core/src/main/java/org/wso2/testgrid/core/command/GenerateReportCommand.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/aws/AWSManager.java, reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngine.java
Fixing log issues in testgrid classes
Better logs
Fixing log issues in testgrid classes:
AWSManager: print the missing credential env var names.
TestReportEngine: print the report file path.
GenerateReportCommand: fix the log path.
=> Fixing log issues in testgrid classes

distribution/assembly.xml, distribution/pom.xml, jenkins-pipelines/Jenkinsfile, jenkins-pipelines/continuous-delivery/Jenkinsfile, version.md
> The Jenkins build fails due to the changes pattern in name of testgrid distribution.
> Resolves #449
> Use a standard name for the distribution so that modification of the distribution name in the Jenkins pipeline is avoided
> Renamed the file when copying in CD pipeline script
> Avoided packing the directory with milestone and version into the distribution zip
=> Fix wrong testgrid distribution referred in the jenkins pipeline

common/src/main/java/org/wso2/testgrid/common/util/StringUtil.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java
Randomize the cloudformation script name at runtime  to support running multiple cloudformation scripts in parallel. 
Resolves #456
Support scaling.
Randomize the script name under the test-plan's infrastructure section.
=> Randomize the cloudformation script name at runtime 

jenkins-pipelines/continuous-delivery/Jenkinsfile
Clean out the workspace of testgrid CD pipeline at first.
Workspace may contain stale files otherwise.
Proper function of Testgrid continuous delivery.
deleteDir() pipeline step is added as the very first step.
=> Clean out the workspace of testgrid CD pipeline at first.

docs/Infrastructure-Deployment-Scenarios-Repository-Structure.md
Scenario repo creators can also specify the scenarion directory via cenarioDir element to point to where the scenarios are located
Easier config
=> Scenario repo creators can also specify the scenarion directory via cenarioDir element to point to where the scenarios are located

README.md
Setting the proper testgrid live URL
https://testgrid-live.private.wso2.com/testgrid/dashboard/
First time users need to see the proper URL.
=> Setting the proper testgrid live URL

automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterResultCollector.java, distribution/bin/log4j2.xml
> Removes persistence of large error response sampler data returned by the tests.
> Resolves #451 
> Remove test failure sampler data persistence
> The failure messages are written in to the log file instead of the database.
=> Fix build failure caused by large test failure responses

deployment/src/main/java/org/wso2/testgrid/deployment/deployers/AWSDeployer.java
Resolves #455 
Add a log message to reflect that testgrid process is waiting on a URL to be ready.
And further adds debug logs to see what values are skipped from the cloudformation output values.
=> Add meaningful log message for waiting logic.

automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterExecutor.java, automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterResultCollector.java, dao/src/main/java/org/wso2/testgrid/dao/uow/TestCaseUOW.java
> Contains the fix for exception caused when attempted to concurrently persist test cases.
> Resolves #424 
> Handling persistence of concurrent scenario samplers properly.
> Test case persistence is done after all the test cases have completed for a particular scenario. 
> The ResultCollector writes the test results to a concurrent list and this list is used later in the JMeterExecutor to persist the test cases to the database.
=> Fix failure in persistence of concurrent scenario samplers

jenkins-pipelines/continuous-delivery/Jenkinsfile
ATM Jenkins Job to deploy TestGrid to its environments waits in at one step excepting permission as a user input to continue. Due to this reason the job keeps hanging until the input is given. We needs to avoid that.
Fixes #471 
Inform the team about this wait and also keep a time-out to automatically abort the job.
The jenkins pipeline is modified as to execute user-input request inside a time-out. Also add email sending command at the time of user-input request.
=> Time-out and email option for CICD user-input step.

reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngine.java
> Removes unwanted history from the final report and generates the final report based on the latest test run for each infra combination.
> Resolves #362 
> The final report should only contain the details related to the latest test run for each infra combination
> Rework report element construction logic in TestReportEngine#constructReportElements
=> Generate final report using the latest test run for each infra combination

automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterExecutor.java
> Contains changes related to persisting the test scenario instead of individual test cases.
> Resolves #474 
> Persist the test scenario after all tests of the particular scenario are executed and avoid persisting individual test cases.  
> Rewrite code for persistence in JmeterExecutor#execute
=> Rewrite test case persistence logic to persist the test scenario

jenkins-pipelines/continuous-delivery/Jenkinsfile
WSO2 Jenkins require all jobs to have a node label
Hence, using the COMPONENT_ECS label out of the available two.
=> Set COMPONENT_ECS as the node label for continuous-delivery pipeline

web/src/main/java/org/wso2/testgrid/web/sso/SSOSessionCheckFilter.java, web/src/main/java/org/wso2/testgrid/web/utils/Constants.java, web/src/main/react-dashboard/src/components/DeploymentPatternView.js, web/src/main/react-dashboard/src/components/InfraCombinationView.js, web/src/main/react-dashboard/src/components/ProductStatusView.js, web/src/main/react-dashboard/src/components/ScenarioView.js, web/src/main/react-dashboard/src/components/TestCaseView.js, web/src/main/react-dashboard/src/components/TestRunView.js, web/src/main/react-dashboard/src/constants.js, web/src/main/react-dashboard/src/registerServiceWorker.js, web/src/main/webapp/WEB-INF/web.xml
>When a session-invalidated-user tries to view dashboard, he should return to the login-page of the dashboard.
Fixes #521 
>  Since the pages are cached, ATM the only requests that goes to back-end from a session-invalidate-user are the backend-API calls. Customized the session check in the backend as to return 401 for any backend-API call from invalid /null session request. From react, the dashboard is redirected to its login page when a 401 is received for a backend
=> Implement method to handle dashboard redirection for backend APIs when session expires.

common/src/main/java/org/wso2/testgrid/common/config/ConfigurationContext.java, dao/src/main/java/org/wso2/testgrid/dao/EntityManagerHelper.java, web/src/main/java/org/wso2/testgrid/web/operation/JenkinsJobConfigurationProvider.java, web/src/main/java/org/wso2/testgrid/web/operation/JenkinsPipelineManager.java, web/src/main/java/org/wso2/testgrid/web/plugins/AWSArtifactReader.java, web/src/main/java/org/wso2/testgrid/web/sso/SSOSessionCheckFilter.java
> Contains changes related to refactoring ConfigurationContext to move from org.wso2.testgrid.common.util to org.wso2.testgrid.common..config package.
> Resolves #525 
=> Move ConfigurationContext to org.wso2.testgrid.common.config package

core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java
> Contains the fix for resolving absolute paths provided in job-config.yaml
> Resolves #537
> Enable providing absolute paths for paths specified in job-config.yaml
> The default paths are the ones specified in job-config.yaml. Resolving the path only if the parent directory is present AND relativePaths boolean is set to false in job-config.yaml. 
> Provide high-level details about the samples related to this feature
> List any other related PRs
> Describe migration steps and platforms on which migration has been …
=> Fix resolving absolute paths in job-config.yaml

automation/pom.xml, common/pom.xml, core/pom.xml, dao/pom.xml, deployment/pom.xml, distribution/pom.xml, infrastructure/pom.xml, issue_template.md, logging/pom.xml, pom.xml, pull_request_template.md, reporting/pom.xml, test/coverage/pom.xml, web/pom.xml
Rename Testgrid Framework to Testgrid Project in poms.
Testgrid is not a framework. It is a project in itself with ultimate plan
to provide a SaaS.
Fixed typo in the artifactId of infrastructure module.
=> Rename Testgrid Framework to Testgrid Project in poms

web/src/main/react-dashboard/src/components/TestRunView.js
**Purpose**
Fixes #544 
**Approach**
The session-id was not included when trying to fetch test-log file from the backend.  Then the backend interpret it as a request from invalid user and a 401 is sent. Then the dashboard was redirected to Login page. The changes are to attach the session cookie with the fetch request so that the backend identifies its from a user with valid/ invalid session.
#373
=> Fix incorrect redirection to the login page when downloading a Test-log file

core/pom.xml, deployment/pom.xml, distribution/pom.xml, pom.xml
**Purpose**
> Contains changes needed to fix the build failure caused by the wrong dependency used for infrastructure module.
> Resolves #547 
**Goals**
Fix build failure
**Approach**
Include the correct name of infrastructure module in other necessary modules and parent pom.
=> Fix build failure caused by wrong dependency used for infrastructure module

common/src/main/java/org/wso2/testgrid/common/ShellExecutor.java, deployment/src/main/java/org/wso2/testgrid/deployment/deployers/ShellDeployer.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/ShellScriptProvider.java
**Purpose**
Contains improvements related to honouring the return status of infra provisioning script.
Resolves #337 
**Goals**
TestGrid should handle the infra creation failure gracefully when shell scripts are used.
**Approach**
Improve ShellScriptProvider#provision to consider for the boolean value returned by the ShellExecutor#executeCommand when returning the InfraProvisionResult
=> Improve testgrid to honor the  return status of infra provisioning script

common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java, core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java, core/src/test/java/org/wso2/testgrid/core/command/GenerateTestPlanCommandTest.java, core/src/test/java/org/wso2/testgrid/core/command/RunTestPlanCommandTest.java, core/src/test/resources/test-plan-01.yaml
**Purpose**
To persist testplan at the generate-test-plans step instead of run-testplan step. This will also resolve #514 and #431.
**Goals**
TestGrid should persist test-plan information to DB at the generate-testplan step. 
**Approach**
Persisted testplan to the database when executing generate-testplan command and saved the testplan.yaml with the testplan-id. When running run-test-plan command, it will fetch the appropriate testplan object from database using the id.
**Related Issues**
#431, #552
=> Persist TestPlan to database at generate-TestPlan step

common/src/main/java/org/wso2/testgrid/common/config/InfrastructureConfig.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java, jenkins/pipelines/Jenkinsfile
**Purpose**
Fixes #558 
**Approach**
The same Infrastructure-config object was added to an array-list in a loop. Thus all configs were becoming identical. Fixed by doing clone before adding to the array-list.
=> Fix for multiple test-plan yaml files containing same infrastructure combination

deployment/src/main/java/org/wso2/testgrid/deployment/DeploymentUtil.java, deployment/src/main/java/org/wso2/testgrid/deployment/deployers/ShellDeployer.java
**Purpose**
Contains changes related to adding the necessary host information in ShellDeployer.
Resolves  #561
**Goals**
Fixing the test failures occurring due to bugs in TestGrid
**Approach**
Hard-coded tomcat host information
Retrieved other host information of the deployment through deployment.json generated by deploy.sh
=> Fix scenario failures on K8S due to missing host information

common/src/main/java/org/wso2/testgrid/common/config/ConfigurationContext.java, common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/aws/AMIMapper.java, infrastructure/src/test/java/org/wso2/testgrid/infrastructure/AWSProviderTest.java, web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java, web/src/main/java/org/wso2/testgrid/web/plugins/AWSArtifactReader.java
**Purpose**
Contains changes related to modifying AWS Client Builders to use PropertiesFileCredentialsProvider.
Resolves #491
**Goals**
Avoiding environment variables for credentials and using existing config.properties.
**Approach**
Modify AWS Client Builders usage to use  PropertiesFileCredentialsProvider.
- cloudformation
Define the following properties in config.properties
`accessKey`
`secretKey`
- kubernetes
Add `openrc.sh` file to `infrastructureRepository` specified …
=> Modify AWS Client Builders usage to read config.properties for credentials

common/src/main/java/org/wso2/testgrid/common/TestGridConstants.java, common/src/main/java/org/wso2/testgrid/common/config/ConfigurationContext.java, core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java
**Purpose**
Resolve #576.
**Goals**
With this PR, it would be possible to pass wum credentials as input parameters to the infra/deployment script.
=> Obtain wum credentials from the config file and pass it to CF script

jenkins/pipelines/continuous-delivery/Jenkinsfile
**Purpose**
To change the copy-location of TestGrid distribution as following:
> Previously: /testgrid/jenkins-home/workspace/WSO2-TestGrid.zip
> New: <TESTGRID_HOME>/testgrid-dist/WSO2-TestGrid.zip
The reason is to consolidate working directories of Jenkins and TestGrid.
Partially fixes #526
=> Change copy-location of TestGrid distrubution in CI/CD.

common/src/main/java/org/wso2/testgrid/common/config/InfrastructureConfig.java, common/src/main/java/org/wso2/testgrid/common/config/Script.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java
**Purpose**
Fixes the bug in generation of the unique name for infrastructure provisioning script.
Resolves #599 and #582 
**Goals**
Resolve the bug in unique name generation for infrastructure provisioning script
**Approach**
Introduce clone() to Provisioner and Script.
=> Fix lengthy and duplicate names generated for infrastructure provisioning scripts

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/CloudFormationScriptPreprocessor.java
**Purpose**
If the deletion policy is set to snapshot, then, AWS makes a backup of the database before deletion. But, AWS has a limitation on how many manual snapshots we can create (100).
Since testgrid re-spawns CF stacks again and again, we need to remove this policy. 
Fixes #423 
**Approach**
Check for the DeletionPolicy element at the CF script pre-process stage and remove it.
=> Remove DeletionPolicy element at CF-script pre-process step

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java
**Purpose**
AWS region is mentioned under the infrastructureConfig -> scripts. However it was not read properly. This fixes the issue and read the property properly.
Fixes #496 
**Approach**
Earlier the method was searching the parameter `region` in infrastuctureConfig's parameters.
Changed it to read from;
` infrastructureConfig --> provisioner--> script--> parameters --> 'region' parameter`
=> Resolve error in getting AWS-region from infrastructure-configurations file.

automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterResultCollector.java
**Purpose**
Removes response data from testcase failure message.
Resolves #608 
**Goals**
Resolve database persistence failure.
**Approach**
Remove response data from testcase failure message.
=> Fix database persistence failure due to length of failure_message

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/CloudFormationScriptPreprocessor.java
**Purpose**
Contains changes related to modifying the DeletionPolicy to "Delete"
Resolves #612
**Goals**
Avoid creating DBInstance snapshots upon stack deletion.
**Approach**
Modify DB instance deletion policy to "Delete"
=> Fix DB Snapshot deletion 

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/aws/AMIMapper.java
**Purpose**
To resolve #628 
**Goals**
To introduce OSVersion as a AMI lookup parameter.
=> Add OSVersion as a infrastructure parameter for AMI lookup

deployment/src/main/java/org/wso2/testgrid/deployment/DeploymentUtil.java, deployment/src/main/java/org/wso2/testgrid/deployment/deployers/ShellDeployer.java
**Purpose**
Contains changes related to setting the host details as `serverHost` and `serverPort` from deployment.json.
Resolves #616 
**Goals**
Provide the correct hostnames and ports for JMeter test execution.
**Approach**
Rework creation of DeploymentCreationResult in `DeploymentUtil#getDeploymentCreationResult`.
=> Set host details from deployment.json in the proper format

common/src/main/java/org/wso2/testgrid/common/TestScenario.java, common/src/main/java/org/wso2/testgrid/common/config/ScenarioConfig.java, common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java, core/src/test/resources/test-plan-01.yaml, core/src/test/resources/workspace/testgrid.yaml, reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngine.java, reporting/src/main/java/org/wso2/testgrid/reporting/model/ReportElement.java, reporting/src/main/resources/templates/report_element.mustache, web/src/main/java/org/wso2/testgrid/web/api/APIUtil.java, web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java, web/src/main/java/org/wso2/testgrid/web/bean/ScenarioSummary.java, web/src/main/java/org/wso2/testgrid/web/bean/ScenarioTestCaseEntry.java, web/src/main/react-dashboard/src/components/TestRunView.js
**Purpose**
Contains changes related to displaying scenario names in the dashboard and final report using testgrid.yaml. 
Resolves #603
**Goals**
To display meaningful names for scenarios in the dashboard and the final report.
**Approach**
- Map the names in testgrid.yaml in scenario repository and parse the description of each scenario.
- Persist to database and retrieve to dashboard and report
=> Rework reading testgrid.yaml and improve report and dashboard view

core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java
**Purpose**
Contains changes related to modifying GenerateTestPlanCommand to:
- skip missing properties in testgrid.yaml
- ignore incomplete testgrid.yaml
Resolves #647 
**Goals**
Improve TestGrid code when reading testgrid.yaml
**Approach**
Modify `GenerateTestPlanCommand#buildTestgridYamlContent`
=> Improve reading of testgrid.yaml to skip missing properties and ignore if incomplete

core/src/main/java/org/wso2/testgrid/core/ScenarioExecutor.java, core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java
**Purpose**
Contains changes related to setting the `testLocation` based on the value of the property `dir` from test-plan yaml. 
Resolves #651
**Goals**
Refer to the scenario directory by the correct value specified in the test-plan-*.yaml
**Approach**
- Rework ScenarioExecutor#execute
- Rework TestPlanExecutor#runScenarioTests
=> Modify scenario testLocation path to refer to directory using scenario#getDir

jenkins/pipelines/continuous-delivery/Jenkinsfile
**Purpose**
Contains changes to avoid copying unnecessary artefacts from testgrid build job in testgrid-prod-deploy.
Resolves #303 
**Goals**
Avoid time and space taken to copy unnecessary files from testgrid job.
**Approach**
Added a filter when using copyArtifacts plugin in the pipeline
=> Add a filter to copyArtifact plugin in continuous-delivery pipeline

dao/src/main/java/org/wso2/testgrid/dao/EntityManagerHelper.java, dao/src/main/java/org/wso2/testgrid/dao/repository/AbstractRepository.java, dao/src/main/java/org/wso2/testgrid/dao/repository/DeploymentPatternRepository.java, dao/src/main/java/org/wso2/testgrid/dao/repository/ProductRepository.java, dao/src/main/java/org/wso2/testgrid/dao/repository/TestPlanRepository.java
**Purpose**
The purpose of this PR is to fix dashboard updating issue when database entry change. Further resolving inconsistency of redeploying web app when database entry change. 
Resolves #661 
**Goals**
Since Entity Manager retrieves data from its associated cache and if we completely bypass the entity manager cache for updating the database, the state held by the cache won't be updated to the updated database state. Hence in order to avoid this inconsistency, it is required to clear the cache when we retrieve date.
**Approach**
In order to get data forcefully from the database instead of caching, called refresh() method of Entity Manager for a returned entity. Further, if List of objects returned by a query is not itself an Entity. Therefore in that kind of case, in order to refresh …
=> Fix Dashboard Updating Issue

pom.xml, web/pom.xml, web/src/main/java/org/wso2/testgrid/web/sso/SSOSessionCheckFilter.java
**Purpose**
The purpose of this PR is to fix TESTGRID dashboard accessing issue when SSO is disabled. 
This resolves wso2/testgrid#694, wso2/testgrid#693
**Goals**
All requests are passing through the SSOSessionCheckFilter.  SSOSessionCheckFilter doesn't allow to access the dashboard when SSO is disabled. Hence modified the doFilter method in the SSOSessionCheckFilter to access the dashboard when disabling the SSO.
**Approach**
N/A
N/A
N/A
N/A
**Training**
N/A
N/A
**Marketing**
N/A
- Unit tests 
N/A
N/A
- Ran FindSecurityBugs plugin and verified …
=> Fix dashboard accessing issue when SSO is disabled

common/src/main/java/org/wso2/testgrid/common/TestGridConstants.java, common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java, core/src/main/java/org/wso2/testgrid/core/command/FinalizeRunTestplan.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateReportCommand.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java, core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java, distribution/bin/log4j2.xml, web/src/main/java/org/wso2/testgrid/web/api/LogEventSocketMediator.java, web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java
**Purpose**
Contains changes related to making the test-run log file name more context aware.
**Goals**
Improve logging implementation.
**Approach**
The new log file will be named as `<testgrid-home>/<product-name>/logs/<deployment_pattern>_<infrastructure-combination/uuid>_<build-number>.log`
=> Improve test-run log file name

common/src/main/java/org/wso2/testgrid/common/TestPlan.java, common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java, core/src/test/java/org/wso2/testgrid/core/command/GenerateTestPlanCommandTest.java, core/src/test/java/org/wso2/testgrid/core/command/RunTestPlanCommandTest.java, core/src/test/resources/test-plan-01.yaml
**Purpose**
Contains changes related to persisting the Jenkins build number to the database.
Resolves #710 
**Goals**
- To clean the database periodically
- Make the report name generated for each build more context aware.
**Approach**
Replace the `test_run_number` with `build_number` in the database.
Get the build number as an input to the generate-test-plan command
=> Support persisting Jenkins build number

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java, infrastructure/src/test/java/org/wso2/testgrid/infrastructure/AWSProviderTest.java
**Purpose**
Fixed test grid infrastructure creation fail issue when AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are not in environment variables.
**Goals**
Fix https://github.com/wso2/testgrid/issues/716
**Approach**
Remove unnecessary environment variable validation
Fixed https://github.com/wso2/testgrid/issues/716
Does not effected
https://github.com/wso2/testgrid/pull/511
Ubuntu x64 16.04.4 LTS, JDK 1.8.0_171-b11, MySQL 5.7.21
=> [AWS] Testgrid infrastructure creation failed when AWS credentials are not in environment variables.

core/src/main/java/org/wso2/testgrid/core/command/FinalizeRunTestplan.java, dao/src/main/java/org/wso2/testgrid/dao/repository/TestPlanRepository.java, dao/src/main/java/org/wso2/testgrid/dao/uow/TestPlanUOW.java
**Purpose**
Contains changes related to improving `finalize-run-testplan` command.
Resolves #713 
**Goals**
Improve `finalize-run-testplan` command: 
- to update testplans based on the Jenkins build number
- to be able to run as cron job
**Approach**
Rework the logic to expect more arguments. Considers the build number to update testplans if provided. Else, updates all the testplans that has erroneous statuses that are older than 24 hours.
=> Improve finalize-run-testplan logic

jenkins/pipelines/continuous-delivery/Jenkinsfile
**Purpose**
This fix is required to change the testgrid webapp context to root.
=> Update testgrid.war to ROOT.war

dao/src/main/java/org/wso2/testgrid/dao/repository/TestPlanRepository.java, infrastructure/src/test/java/org/wso2/testgrid/infrastructure/AWSProviderTest.java
**Purpose**
The purpose of this PR is to fix incorrect deployment patterns showing. This resolves #723.
**Goals**
Test Grid dashboard displayed non-existent deployment patterns in the deployment patterns displaying page. In other words, when we click on a product and view the deployment patterns of that product, it displayed incorrect/non-existent deployment patterns. Hence in order to fix the issue, modified the test plans retrieving query. Further fixed local build failure issue by fixing failed test cases and removing unnecessary test cases.
**Approach**
N/A
N/A
N/A
N/A
**Training**
N/A
N/A
**Marketing**
N/A
- Unit tests 
N/A
N/A
- Followed secure coding …
=> Fix incorrect deployment patterns showing

automation/src/main/java/org/wso2/testgrid/automation/Test.java, automation/src/main/java/org/wso2/testgrid/automation/executor/TestExecutor.java, common/src/main/java/org/wso2/testgrid/common/InfrastructureProvider.java, common/src/main/java/org/wso2/testgrid/common/ShellExecutor.java, common/src/main/java/org/wso2/testgrid/common/config/ScenarioConfig.java, core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java, docs/Infrastructure-Deployment-Scenarios-Repository-Structure.md, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/OpenStackProvider.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/ShellScriptProvider.java, infrastructure/src/test/java/org/wso2/testgrid/infrastructure/AWSProviderTest.java, infrastructure/src/test/resources/scenarios/cleanup.sh, infrastructure/src/test/resources/scenarios/init.sh
**Purpose**
Standardizes the provision of infrastructure need to execute scenario tests through two scripts. 
Resolves #725
**Goals**
Provide a standardized approach to provision infrastructure required for scenario tests. Eg. tomcat deployment for IS scenarios, MSF4J services for APIM scenarios
**Approach**
Support running a `init.sh` before running scenarios to provision necessary infrastructure and a `cleanup.sh` after running scenarios to destroy provisioned infrastructure.
The scenario test repos should contains these two scripts if additional infrastructure is required and this should be specified with `scripts` element in testgrid.yaml in the same repo as follows.
```
scenarioConfig:
scenarios:
-
name: scenario03
description: 'App Development with APIs'
dir: scenario03
-
name: …
```
=> Support execution of init and cleanup scripts to provision infrastructure required for samples

jenkins/pipelines/continuous-delivery/Jenkinsfile
**Purpose**
Contains changes related to copying the deployment-tinkerer war file from latest testgrid artifacts.
Resolves #758
**Goals**
Fix failure in the execution of cd pipeline.
=> Add deployment-tinkerer to CD pipeline filter for copying artifacts

common/src/main/java/org/wso2/testgrid/common/TestGridConstants.java
**Purpose**
Since testgrid.yaml only has a usage within TestGrid, it is been kept hidden.
Fixes #728 
**Goals**
Avoid exposing internal files to outside.
**Approach**
Change "testgrid.yaml" as ".testgrid.yaml".
=> Make testgrid.yaml a hidden file

web/src/main/java/org/wso2/testgrid/web/api/ProductService.java, web/src/main/java/org/wso2/testgrid/web/plugins/AWSArtifactReader.java, web/src/main/java/org/wso2/testgrid/web/plugins/ArtifactReadable.java, web/src/main/react-dashboard/src/components/ProductStatusView.js
**Purpose**
The purpose of this PR is to fix report downloading issue through the Test grid dashboard. This resolves #765
**Goals**
Since the report downloading API returns stream it doesn't convert to file when we invoke API through fetch. Hence added HEAD API and it verifies the existence of the report and it doesn't return a body as well. Thereafter check the response code of HEAD API invocation and invoke the GET API to download the report. The GET API will be invoked in the callback of the first request.
**Approach**
N/A
N/A
N/A
N/A
**Training**
N/A
N/A
**Marketing**
N/A
- Unit tests 
N/A
N/A
- Followed secure coding standards in …
=> Fix the report downloading issue through the dashboard.

common/src/main/java/org/wso2/testgrid/common/TestGridConstants.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java
**Purpose**
Since testgrid.yaml only has a usage within TestGrid, it is been kept hidden with recent updates.
But however we should still support if the testgrid.yaml is not hidden.
Fixes #767
**Goals**
Keep backward compatibility with old configurations.
**Approach**
When referring to testgrid yaml file, check if there exists a testgrid yaml file as a hidden file. If so, proceed with that.
#760
=> Add backward-compatibility between old/new testgrid yaml file.

common/src/main/java/org/wso2/testgrid/common/TestGridConstants.java, common/src/main/java/org/wso2/testgrid/common/util/FileUtil.java, core/pom.xml, core/src/main/java/org/wso2/testgrid/core/ScenarioExecutor.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java, core/src/main/resources/run-scenarioTemplate.vm, pom.xml
**Purpose**
When there is no run-scenario.sh file is provided with a scenario, testgrid have to make one including the available test-scripts.
Fixes #745 
**Approach**
Receive list of test-script files and prepare run-scenario script using apache-velocity.
The test-scripts will be added in alphabetical order.
=> Auto generate run-scenario script file for test scenarios

core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java, core/src/test/java/org/wso2/testgrid/core/command/GenerateTestPlanCommandTest.java, core/src/test/java/org/wso2/testgrid/core/command/RunTestPlanCommandTest.java, core/src/test/resources/job-config.yaml, jenkins/pipelines/Jenkinsfile, jenkins/pipelines/test-jobs/wso2apim-2.1.0-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2apim-2.2.0-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2ei-6.1.1-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2is-5.3.0-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2is-5.5.0-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2is5.4.0LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2is5.4.1LTS/Jenkinsfile
**Purpose**
The purpose of this PR is to resolve alternative directory creating and scenario test running failure for the same job.  
This resolves #757
**Goals**
In order to fix this issue modified the test plans creating command. Therefore removed 'working-dir' parameter in the test plans creating command. When creating test plans read the file path of the job-config.yaml and if it contains 'TestGrid_Home/jobs/*' pattern, create test-plans directory and test plans yaml files inside the parent directory of job-config.yaml. Otherwise, create a directory inside the TestGrid_Home/jobs and name it as <Product_Name> and use it to create and store test-plans directory and test plans.
**Approach**
N/A
N/A
N/A
N/A
**Training**
N/A …
=> Fix the alternative directory creating and scenario test running failure for the same job

jenkins/pipelines/Jenkinsfile, jenkins/pipelines/continuous-delivery/Jenkinsfile, jenkins/pipelines/test-jobs/wso2apim-2.1.0-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2apim-2.2.0-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2ei-6.1.1-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2is-5.3.0-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2is-5.5.0-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2is5.4.0LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2is5.4.1LTS/Jenkinsfile
**Purpose**
testgrid-prod-deploy job should first delete the old wso2-testgrid before unpacking the dist
Fixes #791 
**Goals**
Fixes
```
[main] INFO org.wso2.testgrid.core.Main - TestGrid Home	: /testgrid/testgrid-home
Exception in thread "main" java.lang.NoSuchMethodError: org.wso2.testgrid.common.util.TestGridUtil.deriveLogFilePath(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
at org.wso2.testgrid.core.command.GenerateTestPlanCommand.execute(GenerateTestPlanCommand.java:138)
at org.wso2.testgrid.core.command.CommandHandler.execute(CommandHandler.java:124)
at org.wso2.testgrid.core.Main.main(Main.java:47)
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
```
**Approach**
=> testgrid-prod-deploy job should first delete the old wso2-testgrid before unpacking the dist

automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterExecutor.java, automation/src/main/java/org/wso2/testgrid/automation/parser/FunctionalTestResultParser.java, automation/src/main/java/org/wso2/testgrid/automation/parser/JMeterResultParserFactory.java, common/src/main/java/org/wso2/testgrid/common/ShellExecutor.java, common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java, core/pom.xml, core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java, core/src/test/java/org/wso2/testgrid/core/TestPlanExecutorTest.java, core/src/test/java/org/wso2/testgrid/core/command/RunTestPlanCommandTest.java, core/src/test/resources/log4j2.xml, pom.xml, test-scripts/local-is-deployment/Solutions/solution01/jmeter/01-TestIS540.jmx, test-scripts/local-is-deployment/Solutions/solution01/run-scenario.sh
**Purpose**
Print a summary of the execution at the end of run-testplan
Fixes #517 
**Goals**
Better readability of the log.
**Approach**
similar to maven
```
[19:40:15,550] There are test failures...
[19:40:15,550] Failed tests:
[19:40:15,555]   Sample scenario 02::Sample Testcase 02: fail
[19:40:15,555]   Sample scenario 02::Sample Testcase 03: fail
[19:40:15,555] 
[19:40:15,555] Tests run: 3, Failures/Errors: 2
[19:40:15,555] 
[19:40:15,558] ------------------------------------------------------------------------
[19:40:15,560] Test Plan Summary for {DBEngine: "mysql"}
[19:40:15,560] Sample scenario 01 ................................. SUCCESS
[19:40:15,560] Sample scenario 02 ................................. FAIL
[19:40:15,560] …
```
=> Print a summary of the execution at the end of run-testplan

automation/pom.xml, automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterExecutor.java, common/pom.xml, common/src/main/java/org/wso2/testgrid/common/TestGridConstants.java, common/src/main/java/org/wso2/testgrid/common/util/FileUtil.java, common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java, jenkins/pipelines/test-jobs/wso2apim-2.1.0-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2apim-2.2.0-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2ei-6.1.1-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2is-5.3.0-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2is-5.5.0-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2is5.4.0LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2is5.4.1LTS/Jenkinsfile, web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java, web/src/main/java/org/wso2/testgrid/web/bean/ScenarioSummary.java, web/src/main/java/org/wso2/testgrid/web/utils/Constants.java, web/src/main/react-dashboard/src/components/TestRunView.js
**Purpose**
Fixes #795 
Now the logs are persisted in S3 as below;
The user is also able to download per-scenario results as below;
=> Option to persist test scenario results in S3 and download per-scenario

common/src/main/java/org/wso2/testgrid/common/Product.java, core/src/main/java/org/wso2/testgrid/core/command/FinalizeRunTestplan.java, dao/src/main/java/org/wso2/testgrid/dao/repository/ProductRepository.java, dao/src/main/java/org/wso2/testgrid/dao/uow/ProductUOW.java, jenkins/pipelines/test-jobs/wso2apim-2.1.0-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2apim-2.2.0-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2ei-6.1.1-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2is-5.3.0-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2is-5.5.0-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2is5.4.0LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2is5.4.1LTS/Jenkinsfile, web/src/main/java/org/wso2/testgrid/web/api/APIUtil.java, web/src/main/java/org/wso2/testgrid/web/api/ProductService.java, web/src/main/java/org/wso2/testgrid/web/bean/Product.java, web/src/main/java/org/wso2/testgrid/web/bean/ProductStatus.java, web/src/main/react-dashboard/src/components/ProductStatusView.js
**Purpose**
The purpose of this PR is to add last success field into TG home page. This resolves #797.
**Goals**
In order to increase the sense of displaying data on the home page, removed the latest build column from the home page and add the last success column. To maintain the product status modified the finalize-test-plan command. Loop all test plan files and get status of the test plan. If one of the test plans is in the FAIL status update the last_failure_timestamp column in the product table. If all test plans are in success status update the last_success_timestamp.
**Approach**
- Confirmed that …
=> Add last success column to the TG home page

automation/src/main/java/org/wso2/testgrid/automation/TestEngine.java, automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterExecutor.java, automation/src/main/java/org/wso2/testgrid/automation/executor/ShellTestExecutor.java, automation/src/main/java/org/wso2/testgrid/automation/executor/TestExecutorFactory.java, automation/src/main/java/org/wso2/testgrid/automation/reader/JMeterTestReader.java, automation/src/test/java/org/wso2/testgrid/automation/executor/JMeterExecutorTest.java, common/src/main/java/org/wso2/testgrid/common/TestGridConstants.java, common/src/main/java/org/wso2/testgrid/common/TestPlan.java, common/src/main/java/org/wso2/testgrid/common/config/JobConfigFile.java, common/src/main/java/org/wso2/testgrid/common/util/DataBucketsHelper.java, common/src/main/java/org/wso2/testgrid/common/util/StringUtil.java, common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java, core/src/main/java/org/wso2/testgrid/core/ScenarioExecutor.java, core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java, core/src/test/java/org/wso2/testgrid/core/command/RunTestPlanCommandTest.java, core/src/test/resources/test-plan-01.yaml, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java, infrastructure/src/test/java/org/wso2/testgrid/infrastructure/AWSProviderTest.java, jenkins/pipelines/test-jobs/wso2apim-2.1.0-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2apim-2.2.0-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2ei-6.1.1-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2is-5.3.0-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2is-5.5.0-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2is5.4.0LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2is5.4.1LTS/Jenkinsfile, web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java
**Purpose**
Testgrid need to be able to run product integration tests. For that purpose, we are going to get the testgrid to have,
1. a proper data-passing mechanism through the testgrid's test-plan pipeline (infra -> deploy -> tests), 
2. Support for running generic test scripts in contrast to being jmeter specific. (Deprecated JmeterTestExecutor!)
3. Provide job's properties as input arguments to scripts testgrid execute.
=> Support to run generic test scripts in testgrid for intg tests

automation/src/main/java/org/wso2/testgrid/automation/parser/FunctionalTestResultParser.java, automation/src/main/java/org/wso2/testgrid/automation/parser/ResultParser.java, automation/src/main/java/org/wso2/testgrid/automation/parser/ResultParserFactory.java, automation/src/main/java/org/wso2/testgrid/automation/parser/TestNgResultsParser.java, automation/src/test/java/org/wso2/testgrid/automation/executor/TestNgResultsParserTest.java, automation/src/test/resources/testng-results.xml, web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java
**Purpose**
We need to parse the testng output in order to figure out the test cases that has been run. 
Fixes #828
**Goals**
This is needed for build mail purpose, and for dashboard/report.
**Approach**
Traverses data-buckets to find all `testng-results.xml` files. The they are read via a XMLEventReader.
Each test class is treated as a test case, and is inserted into the db.
=> Introduces a testng integration result parser

common/src/main/java/org/wso2/testgrid/common/TestGridConstants.java, common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java, core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java
**Purpose**
Provide a debug mode for testing purposes.
Fixes #839
**Goals**
For developers.
**Approach**
To enable the developer mode, user need to add a new property to the job-config.yaml via Jenkinsfile.
```
infrastructureRepository: ${INFRA_LOCATION}/'
deploymentRepository: ${INFRA_LOCATION}/
scenarioTestsRepository: ${SCENARIOS_LOCATION}
testgridYamlLocation: ${TESTGRID_YAML_LOCATION}
properties:
DEBUG_MODE: true
PRODUCT_GIT_URL: ${PRODUCT_GIT_URL}
PRODUCT_GIT_BRANCH: ${PRODUCT_GIT_BRANCH}
```
For ex: https://github.com/wso2/testgrid/blob/be69f4533fb692498a4f9a4e97963f0baf5debb1/jobs/wso2am-intg/Jenkinsfile#L91-L103
=> Provide a debug mode for testing purposes

jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
DB license need to be picked from a cfn mapping
* mysql/mariadb - general-public-license
* postgres - postgresql-license
* sqlserver/oracle - license-included
**Goals**
Pick the license automatically depending on the db type
=> DB license need to be picked from a cfn mapping

core/src/main/java/org/wso2/testgrid/tinkerer/UnixClient.java, deployment/src/main/java/org/wso2/testgrid/deployment/deployers/ShellDeployer.java, jobs/intg-test-resources/wso2-intg-test-cfn.yaml, jobs/wso2am-intg/testgrid.yaml, remoting-agent/src/main/bin/init.sh
**Purpose**
Resolves #857 
Resolves #856 
Resolves #855 
**Goals**
TestGrid integration test job execution
**Approach**
#857 
Added the agent registering logic to the ShellDeployer class
#856 
Passed the default database username as a parameter to the cloud formation script.
#855 
Added creation policy section to the cloud formation script. and  installed the cfn-tools in existing centos AMI
=> Integration test related improvements

common/src/main/java/org/wso2/testgrid/common/config/ConfigurationContext.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java
**Purpose**
Make stack deletion waiting configurable. Resolves https://github.com/wso2/testgrid/issues/849
=> Make stack deletion waiting configurable

jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
CloudFormation script for APIM-integration test is having `depends on` property for EC2 instances which pauses creation of EC2 instances until the DB-instance is created. 
But as per the current logic, creation of EC2 instances and creation of DB-instances are independent. Therefore we can remove 'depends on' property which will reduce stack creation time by making the resource creation parallel as per [AWS docs](https://aws.amazon.com/about-aws/whats-new/2013/08/12/aws-cloudformation-introduces-parallel-stack-creation-and-nested-stack-updates/).
Fixes #863
**Goals**
Reduce TestGrid Job execution time.
**Approach**
Let CloudFormation resource creations to be parallel.
- Followed secure coding standards in …
=> Removing "depends on" property in EC2 instances of CF script

common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java, reporting/src/main/java/org/wso2/testgrid/reporting/EmailReportProcessor.java
**Purpose**
To change integration test log file path as to refer from data-bucket of the build.
Fixes #867
=> Change integration-test log file path

common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java
**Purpose**
Add surefire sub-directory to integration-log file path
ex:
><TESTGRID_HOME>/jobs/wso2xy-intg/builds/integration-tests_123456789101112131415161718/data-bucket/**surefire-reports**/
=> Add surefire sub-directory to integration-log file path

automation/src/main/java/org/wso2/testgrid/automation/exception/ReportGeneratorNotFoundException.java, automation/src/main/java/org/wso2/testgrid/automation/report/ReportGeneratorFactory.java, core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java, core/src/main/java/org/wso2/testgrid/tinkerer/UnixClient.java
**Purpose**
Resolves #876 
**Goals**
Get a better understanding of the root cause when an unexpected error occurs during execution of post-test plan actions.
**Approach**
Pass the original message when logging errors
caught Throwable instead of Exception and continued the build
=> Improve logging on post test plan actions

common/src/main/java/org/wso2/testgrid/common/config/ScenarioConfig.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java, dao/src/main/java/org/wso2/testgrid/dao/repository/TestPlanRepository.java
**Purpose**
The purpose of this PR is to modify the latest test plans retrieving query. 
**Goals**
When retrieving latest test plans for a given product, as per the current implementation, it is mainly considered the last modified timestamp of the test plan table and get the latest test plans. Since we stored the test plan number in the DB, it is more appropriate if we consider the maximum of the test plan number for an infra combination and a deployment pattern when we querying the latest test plans for a given product. Hence modified the query in this way. 
- Confirmed that this PR doesn't commit any …
=> Improve latest test plans retrieving query

web/src/main/react-dashboard/src/components/TestRunView.js
**Purpose**
ATM both scenario summary and failed tests are displaying under one pane. This will separate those sections into two tabs.
Test-Run log view also moved to the bottom.
**Approach**
=> Separate scenario summary and failed tests in the TestRun Page.

automation/src/main/java/org/wso2/testgrid/automation/parser/FunctionalTestResultParser.java, automation/src/main/java/org/wso2/testgrid/automation/parser/TestNgResultsParser.java, automation/src/test/java/org/wso2/testgrid/automation/executor/TestNgResultsParserTest.java, common/src/main/java/org/wso2/testgrid/common/Status.java, common/src/main/java/org/wso2/testgrid/common/TestCase.java, core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java, core/src/test/java/org/wso2/testgrid/core/TestPlanExecutorTest.java, reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngine.java, reporting/src/main/java/org/wso2/testgrid/reporting/model/ReportElement.java, reporting/src/main/resources/templates/report_element.mustache, reporting/src/test/java/org/wso2/testgrid/reporting/TestReportEngineTest.java, web/src/main/java/org/wso2/testgrid/web/api/APIUtil.java, web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java, web/src/main/java/org/wso2/testgrid/web/bean/TestCase.java, web/src/main/java/org/wso2/testgrid/web/bean/TestCaseEntry.java
**Purpose**
The purpose of this PR is to modify is_success field in the test_case table.
**Goals**
In current TG implementation, it stores the status of the test case as boolean (i.e. True or False). But when we consider integration test there could be some skipped test cases because of failure of a dependent test case. Hence storing the status of those test cases as Failure is incorrect. Therefore modified the data type of the field and according to that code source also modified. In the new implementation maintain status column as varchar. Further, 'SUCCESS', 'FAIL' and 'SKIP' statuses are maintained.
- …
=> Modify is_success field in the test_case table

automation/src/main/java/org/wso2/testgrid/automation/parser/TestNgResultsParser.java, automation/src/test/resources/artifacts/surefire-reports/TEST-TestSuite.xml
**Purpose**
Resolves #907 
**Goals**
Update the failure message content of both dashboard and the email report
**Approach**.
Read the message attribute from the TestSuite.xml file when possible and if there is no message attribute it will read the first two lines from the stack trace as the failure message
- Unit tests 
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secret? yes
ubuntu 14.04, Jdk8
=> Update displaying failure message of integration tests

automation/src/main/java/org/wso2/testgrid/automation/parser/TestNgResultsParser.java, common/src/main/java/org/wso2/testgrid/common/TestPlan.java, common/src/main/java/org/wso2/testgrid/common/infrastructure/InfrastructureParameter.java, common/src/main/java/org/wso2/testgrid/common/util/FileUtil.java, common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java, core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java, core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java, core/src/main/java/org/wso2/testgrid/infrastructure/InfrastructureCombinationsProvider.java, reporting/src/main/java/org/wso2/testgrid/reporting/EmailReportProcessor.java, reporting/src/main/java/org/wso2/testgrid/reporting/GraphDataProvider.java, reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngine.java, reporting/src/main/java/org/wso2/testgrid/reporting/model/email/InfraCombination.java, reporting/src/main/java/org/wso2/testgrid/reporting/summary/InfrastructureBuildStatus.java, reporting/src/main/java/org/wso2/testgrid/reporting/summary/InfrastructureSummaryReporter.java, reporting/src/main/resources/templates/email_report.mustache, reporting/src/main/resources/templates/summarized_email_report.mustache, reporting/src/test/java/org/wso2/testgrid/reporting/BaseClass.java, reporting/src/test/java/org/wso2/testgrid/reporting/TestReportEngineTest.java, reporting/src/test/java/org/wso2/testgrid/reporting/summary/InfrastructureSummaryReporterTest.java
**Purpose**
Using statistical analysis of builds of the test plans in the current iteration, we should try to determine the exact failing infrastructure that lead to test failures/errors. This is much useful than showing lists of failing infrastructure combinations.
Fixes #919 
**Goals**
Better presentation of testgrid results.
=> Email report: identify test cases that fail due to involvement of two or more infras

automation/src/main/java/org/wso2/testgrid/automation/parser/TestNgResultsParser.java, common/src/main/java/org/wso2/testgrid/common/TestCase.java
**Purpose**
Resolves #942 
**Goals**
The current test-suite.xml does not provide details about the data providers that execute the same test method multiple times. hence they are added to the database by the same name, This change will go through the test cases list and update these duplicate test cases by adding a data provider suffix with an index.
**Approach**
The test cases list will be checked for duplicates and each duplicate will be added a suffix to make them unique entry.
```
Classname#methodname    --> Classname#methodName#data_provider_1
Classname#methodname    --> Classname#methodName#data_provider_2
```
- Ran FindSecurityBugs plugin and verified …
=> Differentiate duplicate test cases by adding data provider suffix

jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
Contains changes related to parameterizing the maven version to get compatible version to run integration tests.
Resolves #974
**Goals**
Build integration test modules successfully.
**Approach**
Parameterized the maven version in the cf script with a default value.
The maven version should be provided as an optional input parameter to the CFN in the testgrid.yaml as below. 
MavenVersion: 3.5.4
=> Parameterize maven version in cf scripts for integration tests

common/src/main/java/org/wso2/testgrid/common/DashboardSetup.java, common/src/main/java/org/wso2/testgrid/common/TestGridConstants.java, common/src/main/java/org/wso2/testgrid/common/config/ConfigurationContext.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java
**Purpose**
Currently Grafana data source is not getting created when SSL is enabled. So the dashboard cannot display the gathered perfomance metrics. These changes will fix this issue
Resolves #973 
**Goals**
Create Grafana data sources successfully 
**Approach**
Bypassed host verification for Grafana URL.
=> Make Grafana product performance dashboard support SSL

common/src/main/java/org/wso2/testgrid/common/util/StringUtil.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/aws/AMIMapper.java
**Purpose**
This PR fixes some issues in JavaDoc comments and `getPropertiesAsString` method
Fixes #988
**Samples**
**Learning**
=> Fix issues in AMIMapper

automation/src/test/java/org/wso2/testgrid/automation/executor/TestNgResultsParserTest.java, common/src/main/java/org/wso2/testgrid/common/TestGridConstants.java, common/src/main/java/org/wso2/testgrid/common/TestPlan.java, common/src/main/java/org/wso2/testgrid/common/util/DataBucketsHelper.java, common/src/main/java/org/wso2/testgrid/common/util/S3StorageUtil.java, common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java, core/src/main/java/org/wso2/testgrid/core/ScenarioExecutor.java, core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateEmailCommand.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java, core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java, core/src/test/java/org/wso2/testgrid/core/command/GenerateTestPlanCommandTest.java, core/src/test/java/org/wso2/testgrid/core/command/RunTestPlanCommandTest.java, core/src/test/resources/test-plan-01.yaml, core/src/test/resources/workspace/deployment/deploy.sh, core/src/test/resources/workspace/infrastructure/infra-provision.sh, deployment/src/main/java/org/wso2/testgrid/deployment/deployers/ShellDeployer.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/ShellScriptProvider.java, infrastructure/src/test/java/org/wso2/testgrid/infrastructure/AWSProviderTest.java, reporting/src/main/java/org/wso2/testgrid/reporting/EmailReportProcessor.java, reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngine.java, reporting/src/test/java/org/wso2/testgrid/reporting/BaseClass.java, web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java
**Purpose**
Fixes #971 
**Goals**
Spread parallel execution into multiple slaves.
**Approach**
**Isolate the parallel block working directories, so that each block run its own**
With this PR, the jobs will run as;
Sample directory;
_Node1_
```
testgridhome -> jobs ->  wso2is-intg -> workspace  (workspace used by generate-testplan command)
-> 2 -> workspace   (workspaces used to run parallel block)
-> 3 -> workspace
-> 4 -> workspace    
-> 5 -> workspace
```
_Node2_
```
testgridhome -> jobs ->  wso2is-intg -> 6 -> workspace   (workspaces used to run parallel block)
-> 7 -> workspace
-> 8 -> workspace
-> 9 -> workspace
-> 10 -> workspace
-> 11 -> workspace
```
The PR include necessary changes to existing Job execution flow in order to make it self-contained.
- Followed …
=> Change TestGrid structure to comply with Jenkins parallel pipeline execution

pom.xml, web/pom.xml, web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java, web/src/main/java/org/wso2/testgrid/web/operation/GrafanaTimeLimitGetter.java, web/src/main/java/org/wso2/testgrid/web/operation/TimeLimitGetter.java, web/src/main/java/org/wso2/testgrid/web/operation/TimeLimits.java
**Purpose**
Resolves:#990 
**Goals**
Display the graphs only in the data available time period
**Approach**
Get the first and last time stamps from influxDB database and set the Grafana url to use these time stamps
=> Set the correct time limits in grafana dashboard url

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java, jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
Resolves:#992 
**Goals**
collect and visualize product performance data for windows
**Approach**
Using User data in cloud formation script telegraf service is started. This will send data to remote influxDB data source same as in Cent OS. 
=> Get performance data from windows

common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java, reporting/src/main/java/org/wso2/testgrid/reporting/EmailReportProcessor.java, reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngine.java, reporting/src/main/java/org/wso2/testgrid/reporting/summary/InfrastructureSummaryReporter.java, reporting/src/main/resources/templates/summarized_email_report.mustache
**Purpose**
Contains improvements related to adding the failed infra combinations (with ERROR status).
Resolves #943
**Goals**
Show infra combinations with errors in the SummarizedEmailReport
=> Add failed infras to Summarized Email Report

reporting/src/main/resources/templates/summarized_email_report.mustache
**Purpose**
Fixes the wrong html structure in mustache template.
=> Fix html structure error in mustache template

common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java, core/src/test/java/org/wso2/testgrid/core/command/RunTestPlanCommandTest.java, core/src/test/resources/workspace/deployment/deploy.sh, core/src/test/resources/workspace/infrastructure/infra-provision.sh, deployment/src/main/java/org/wso2/testgrid/deployment/deployers/ShellDeployer.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/ShellScriptProvider.java
**Purpose**
Resolves #1014 
Shell Provisioner and Shell deployer are updated to use the current TestGrid standard of using databuckets to pass parameters between test phases.
**Goals**
Refactor the Shell script execution to the current TestGrid standard
**Approach**
Every Shell script will receive the data bucket location as a parameter, All the parameters are written to properties files located at that location. required parameters are also read from the same files.
Updated the relevant test cases.
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or …
=> Code refactor to add databucket logic to shell provisioners

common/src/main/java/org/wso2/testgrid/common/config/ConfigurationContext.java, reporting/pom.xml, reporting/src/main/java/org/wso2/testgrid/reporting/EmailReportProcessor.java, reporting/src/test/java/org/wso2/testgrid/reporting/BaseClass.java, reporting/src/test/java/org/wso2/testgrid/reporting/TestReportEngineTest.java
**Purpose**
Contains changes related to retrieving the build details from output.properties locates in S3.
Resolves #1002
**Goals**
To display the correct git revision and location in the summarized email report.
=> Fix incorrect git build details in email report

common/src/main/java/org/wso2/testgrid/common/TestGridConstants.java, common/src/main/java/org/wso2/testgrid/common/util/S3StorageUtil.java, common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java, reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngine.java
**Purpose**
According to the current folder structure, the builds directory is only needed in the S3 bucket. When running the jobs, TestGrid doesn't have to create 'builds' directory and store the data there. The pipeline will sync the data directly to the builds directory in S3.
This PR will remove unnecessary builds directories.
=>  Remove 'builds' directory from unnecessary locations

jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
Seting Java executable path to PATH variable
=> Set Java executable path to PATH variable

packer/resource-ami/config.sh, packer/resource-ami/init.sh, packer/resource-ami/packer-conf.json
**Purpose**
Currently the TestGrid AMIs are created and updated manually. This PR contains the necessary resources to use packer and automate AMI creation.
Fixes #625 #846 #853
Add/Modify/Remove content from existing Testgrid AMIs
If there is a requirement to add/remove/modify an AMI of the TestGrid, you need to do the following steps.
1. Create an instance of the OS you need from OpenStack (TestGrid has its own account)
2. Try out how to do the configuration from a script …
=> Add packer resources to create AMIs.

common/src/main/java/org/wso2/testgrid/common/TestPlan.java, common/src/main/java/org/wso2/testgrid/common/util/S3StorageUtil.java, core/src/main/java/org/wso2/testgrid/core/command/CleanUpCommand.java, core/src/test/java/org/wso2/testgrid/core/command/CleanUpCommandTest.java, dao/src/main/java/org/wso2/testgrid/dao/repository/TestPlanRepository.java, dao/src/main/java/org/wso2/testgrid/dao/uow/TestPlanUOW.java
**Purpose**
Resolves:#1040 
**Goals**
Clean up data of test plans including data base entries in test_plan, test_case, test_scenario and log files in S3
**Approach**
Added new functionality to cleanup sub command and through that user can delete all test plan related data keeping only a specific amount of builds for each infra combination in each job. Graph data is not deleted because all previous emails that contain the graphs are still been used.  
=> Test plan data cleanup

jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
Fixes #1046 
Currently there are 2 paths we have been keeping resource in CentOS instances of the stacks.
1. /opt/wso2/
2. /opt/testgrid/
This will stick all the resource to **/opt/testgrid**
=> Remove using multiple directories for test-resources

packer/resource-ami/config.sh
**Purpose**
Rename oracle db client when adding to AMI
=> Rename oracle db client when adding to AMI

jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
Allow db creation to be disabled with a flag. At the moment in the default CF script Db creation is mandatory, this PR will allow DB creation to be disabled.
=> Allow db creation to be disabled with a flag

core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java, core/src/main/java/org/wso2/testgrid/tinkerer/UnixClient.java
**Purpose**
Since the log message is meaningful enough, there is no need to pollute the log file
with unnecessarily long stack traces.
**Goals**
Better readability of testgrid logs.
=> No need to print entire stack trace for specific errors

core/src/main/java/org/wso2/testgrid/core/ScenarioExecutor.java
**Purpose**
Use test.sh in place of run.scenario.sh
**Goals**
Use test.sh to run tests
**Approach**
Check if the test.sh is existing and use that it. If test.sh is missing use the previous logic 
=> Get test.sh as test excecutor

web/src/main/react-dashboard/src/components/DeploymentPatternView.js, web/src/main/react-dashboard/src/components/TestRunView.js
**Purpose**
Set failed-tests collapsible to be opened by default.
=> Set failed-tests collapsible to be opened by default

common/src/main/java/org/wso2/testgrid/common/TestGridConstants.java, common/src/main/java/org/wso2/testgrid/common/config/DeploymentConfig.java, common/src/main/java/org/wso2/testgrid/common/config/ScenarioConfig.java, core/src/test/java/org/wso2/testgrid/core/command/GenerateTestPlanCommandTest.java, core/src/test/resources/test-plan-01.yaml, core/src/test/resources/workspace/testgrid.yaml
**Purpose**
Along with git repo url, we must get the repo branch as well. It is incorrect to assume that the branch will always be the default/master branch.
**Approach**
Introduced a new property called `remoteBranch` alongside `remoteRepository` for each infra/deploy/test configs.
Yes.
=> Add remoteBranch property into testgrid.yaml to specify the git branch

packer/resource-ami/config.sh
**Purpose**
Set correct JAVA_HOME for openjdk in CentOS
=> Set correct JAVA_HOME for openjdk in CentOS

core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java
**Purpose**
Contains necessary changes to set the name of infra provisioner to the deployment pattern if deploymentConfig is not given in testgrid.yaml. Applicable to CLOUDFORMATION infra provisioners.
=> Set infra-provisioner name to default depl pattern name

common/src/main/java/org/wso2/testgrid/common/config/ConfigurationContext.java, core/src/main/java/org/wso2/testgrid/core/command/FinalizeRunTestplan.java, dao/src/main/java/org/wso2/testgrid/dao/repository/TestPlanRepository.java
**Purpose**
Contains improvements to finalize-run-testplan command to be able to set the running interval through a property in config.properties.
Introduces `FINALIZE_RUN_TESTPLAN_INTERVAL` property
=> Improve finalize-run-testplan to change interval using config.properties

common/src/main/java/org/wso2/testgrid/common/infrastructure/InfrastructureCombination.java, common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java, core/src/main/java/org/wso2/testgrid/infrastructure/InfrastructureCombinationsProvider.java, core/src/test/java/org/wso2/testgrid/infrastructure/InfrastructureCombinationsProviderTest.java, dao/src/main/java/org/wso2/testgrid/dao/dto/TestCaseFailureResultDTO.java, dao/src/main/java/org/wso2/testgrid/dao/uow/TestPlanUOW.java, reporting/src/main/java/org/wso2/testgrid/reporting/GraphDataProvider.java, reporting/src/main/java/org/wso2/testgrid/reporting/summary/InfrastructureSummaryReporter.java, reporting/src/main/resources/templates/summarized_email_report.mustache, reporting/src/test/java/org/wso2/testgrid/reporting/summary/InfrastructureSummaryReporterTest.java, web/src/main/java/org/wso2/testgrid/web/api/APIUtil.java, web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java
**Purpose**
Contains changes required to supporting different aliases used for infrastructure parameters.
**Goals**
**Approach**
Makes use of the properties attached to infrastructure parameters. Each row is considered an individual infrastructure parameter which can have multiple properties to facilitate different input parameters required by infra scripts. All inputs for infra scripts are generated using only the `PROPERTIES` column in the `infrastructure_parameter` table and the `NAME` column is used as a label for displaying in email report and dashboard.
- Confirmed that this PR doesn't commit any …
=> Improve infrastructure parameters handling logic

web/src/main/java/org/wso2/testgrid/web/sso/SSOContextEventListener.java, web/src/main/react-dashboard/src/App.css, web/src/main/react-dashboard/src/App.js, web/src/main/react-dashboard/src/components/DeploymentPatternView.js, web/src/main/react-dashboard/src/components/InfraCombinationView.js, web/src/main/react-dashboard/src/components/ProductStatusView.js, web/src/main/react-dashboard/src/components/ScenarioView.js, web/src/main/react-dashboard/src/components/TestCaseView.js, web/src/main/react-dashboard/src/components/TestRunView.js, web/src/main/react-dashboard/src/constants.js
**Purpose**
This PR fixes dashboard job name caching issue.
In addition, it also,
- Introduces TESTGRID_API_CONTEXT to support pointing to different API endpoint
- Provide a link to go back to dashboard home page
- Improve local dashboard testing support
**Goals**
Better functionality of the dashboard
**Approach**
Previously, we extracted the product name, dep pattern name etc. from the url via `window.location.href.split('/')`. This is error-prone.
This improves the existing logic by using the react-router-dom's url match support. The url parameters added to router can be accessed via `this.props.match.params-{param-name}`.
- Ran FindSecurityBugs plugin and …
=> Fix dashboard job name caching issue

core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java
**Purpose**
Add scenrioConfig name before the  test file path to support multiple scenarioConfigs
=> Append scenrioConfig name to test file path

common/src/main/java/org/wso2/testgrid/common/TestGridConstants.java, common/src/main/java/org/wso2/testgrid/common/TestPlan.java, common/src/main/java/org/wso2/testgrid/common/config/ConfigurationContext.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java, infrastructure/src/test/java/org/wso2/testgrid/infrastructure/AWSProviderTest.java, web/src/main/java/org/wso2/testgrid/web/api/APIUtil.java, web/src/main/java/org/wso2/testgrid/web/bean/TestPlan.java, web/src/main/react-dashboard/src/components/TestRunView.js
**Purpose**
Show logs of each test plan in the TestGrid dashboard.
**Changes required**
Add new column logUrl to test_plan table 
ALTER TABLE `testgriddb`.`test_plan` ADD COLUMN `log_url` VARCHAR(255) NULL DEFAULT NULL AFTER `DEPLOYMENTPATTERN_id`;
Add following to properties to config.properties
KIBANA_ENDPOINT_URL
KIBANA_DASHBOARD_STR
KIBANA_FILTER_STR
=> Enable viewing WSO2 logs for each test plan 

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java, infrastructure/src/test/java/org/wso2/testgrid/infrastructure/AWSProviderTest.java
**Purpose**
Log the ssh access details by probing the created Cloudformation stack
=> Log the ssh access details for *nix instances by probing the created Cloudformation stack

common/src/main/java/org/wso2/testgrid/common/TestPlan.java, core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java, dao/src/main/resources/META-INF/persistence.xml, pom.xml, web/src/main/react-dashboard/src/components/TestRunView.js
**Purpose**
provide a blue ocean link to the user in the test plan view
**Approach**
link is provided as an input parameter to the RunTestPlan command and then it is saved in the database.
- from this PR the create-or-extend-tables property is added to the persistant xml. JPA will modify the existing table in runtime and add new columns. so there is **no need of a manual database migration script.**
- Since this PR introduces Database level changes any jobs running during the PR merge will not revcieve …
=> Access Blueocean console from testplan view in webapp

core/src/main/java/org/wso2/testgrid/core/Main.java
**Purpose**
Exit the testgrid execution once the main thread completes
Currently, there are other Runnables like tinkerer that keep the JVM from exiting
even though the testgrid run-testplan execution is completed.
=> Exit the testgrid execution once the main thread completes

common/src/main/java/org/wso2/testgrid/common/TestGridConstants.java, core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java
**Purpose**
Avoid considering maven-reserved directories as scenarios
=> Avoid considering maven-reserved directories as scenarios

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java, infrastructure/src/test/java/org/wso2/testgrid/infrastructure/AWSProviderTest.java
**Purpose**
After this change users can specify the AWS region the stack should run. 
The region should be specified as an input parameter to the script in testgrid yaml.
Ex:
```
scripts:
inputParameters:
region: "us-east-2"
```
if a region is not specified the default region will be used (us-east-1)
=> Create CloudFormaion stacks in user provided region

core/src/main/java/org/wso2/testgrid/core/command/GenerateEscalationEmailCommand.java, reporting/src/main/java/org/wso2/testgrid/reporting/EscalationEmailGenerator.java
**Purpose**
Option to filter-out jobs use by developer for testing purpose when considering the build-failure-escalation email.
This PR provides option to filter jobs from a regex pattern when selecting the jobs to consider for the build-failure escalation.
=> Filter jobs by a regex in build-failure-escalation email

core/src/main/java/org/wso2/testgrid/core/command/FinalizeRunTestplan.java
**Purpose**
Modify finalize-run-testplan command to run when the `product` input is not given.
=> Modify finalize-run-testplan command

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java
**Purpose**
AWS CLI setup script is not executing after no apt-get error. So adding echo command to avoid it.
=> Remove no apt-get error in aws CLI setup

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java
**Purpose**
AWS provider agent setup only works for Ubuntu environment.
Add missing bash code to set up the agent for CentOS environment.
=> Fix AWS provider agent setup for CentOS environment

jenkins/run-testplan-docker/Dockerfile, jenkins/run-testplan-docker/README.md
**Purpose**
Add Dockerfile used to create run-test-plan container
=> Add Dockerfile used to create run-test-plan container

jobs/intg-test-resources/wso2-intg-test-cfn.yaml
1. To execute Integration test, it required at least  instance type 'm3.2xlarge' performance level. There for change the instance default type to m3.2xlarge. 
2. Refer the windows instance type also to the default value.
=> Change the default instace type

deployment/src/main/resources/kubernetes_helmDeploy.sh
**Purpose**
Resolves #1244 
**Goals**
Changing the Helm Version.
According to [this](https://github.com/helm/helm/issues/5628#issuecomment-485493497), helm 3 introduced a change where it gets the namespace from the local kube config for deployment. The solution given in the above-mentioned ticket cannot be used infra combination running in parallel. 
**Approach**
Helm v2.14.3 will be installed after this change instead of Helm v3.
=> Change helm version

jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
Identity Server Tests are getting the following error.
```
[ADOPT_OPEN_JDK8_MySQL-5.7_CentOS-7.5] [m[32m[10:22:16,340] INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - Caused by: java.io.FileNotFoundException: /opt/testgrid/workspace/product-is/modules/integration/tests-integration/tests-backend/target/carbontmp1575366870802/wso2is-5.7.0/repository/conf/bps.xml (Too many open files)
```
**Goals**
Fix the error by changing file descriptor limit to 65535
**Test …
=> Change file descriptor limit to 65535

jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
Identity Server Tests are getting the following error.
```
[ADOPT_OPEN_JDK8_MySQL-5.7_CentOS-7.5] [m[32m[10:22:16,340] INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - Caused by: java.io.FileNotFoundException: /opt/testgrid/workspace/product-is/modules/integration/tests-integration/tests-backend/target/carbontmp1575366870802/wso2is-5.7.0/repository/conf/bps.xml (Too many open files)
```
**Goals**
Fix the error by changing file descriptor limit to 65535
**Test …
=> Add ulimit -Hn -Sn to view the file limits from the log

jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
Identity Server Tests are getting the following error.
```
[ADOPT_OPEN_JDK8_MySQL-5.7_CentOS-7.5] [m[32m[10:22:16,340] INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - Caused by: java.io.FileNotFoundException: /opt/testgrid/workspace/product-is/modules/integration/tests-integration/tests-backend/target/carbontmp1575366870802/wso2is-5.7.0/repository/conf/bps.xml (Too many open files)
```
**Goals**
Fix the error by changing file descriptor limit to 65535
**Test …
=> Set max file limit

jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
Identity Server Tests are getting the following error.
```
[ADOPT_OPEN_JDK8_MySQL-5.7_CentOS-7.5] [m[32m[10:22:16,340] INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - Caused by: java.io.FileNotFoundException: /opt/testgrid/workspace/product-is/modules/integration/tests-integration/tests-backend/target/carbontmp1575366870802/wso2is-5.7.0/repository/conf/bps.xml (Too many open files)
```
**Goals**
Fix the error by changing file descriptor limit to 65535
**Test …
=> Set both sysctl and ulimit values

jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
Set default JDK to OPEN_JDK11
**Goals**
Set default JDK to OPEN_JDK11
AWS
=> Set default JDK to OPEN_JDK11

jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
Set default JDK to ORACLE_JDK8
**Goals**
Set default JDK to ORACLE_JDK8
Ubuntu18.04
AWS
=> Set default JDK to ORACLE_JDK8

jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
Add if condition to cfn-signal for Unix instance in order to run integration tests for both Ubuntu and centOS
**Goals**
Add if condition to cfn-signal for Unix instance
CentOS 7.5
Ubuntu 18.04
AWS
=> Add if condition to cfn-signal for Unix instance

.gitignore, common/src/main/java/org/wso2/testgrid/common/TestGridConstants.java, common/src/main/java/org/wso2/testgrid/common/config/ConfigurationContext.java, common/src/main/java/org/wso2/testgrid/common/util/DataBucketsHelper.java, core/src/main/java/org/wso2/testgrid/core/util/JsonPropFileUtil.java, core/src/test/java/org/wso2/testgrid/core/command/PropJsonUtilTest.java
**Purpose**
This PR intends to isolate the input parameter added to the .properties file from the Phase class and to add a new feature of using JSON files to support hierarchical Input Parameters.
=> Persisting Input Parameters through JsonPropFile Class

packer/resource-ami/config.sh, packer/resource-ami/init.sh
**Purpose**
1. Newest JDKs are added to the AMI build script.
2. Fix error in using Ubuntu 16.04 base AMI as Ubuntu 18.04
**Goals**
Support new JDKs. Fix AMI mismatch issue.
Ubuntu 18.04
AWS
=> Add new JDKs to AMI build

jobs/intg-test-resources/ballerina-intg-test-cfn.yaml, jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
Add port configs for port 10173 to Identity Server Security group used for Integration tests
**Goals**
Open port 10173
=> Add port 10173 to IS sec-group

core/src/main/java/org/wso2/testgrid/core/phase/TestPhase.java
**Purpose**
fixes #1289 
**Approach**
Add a null check for the IAC provider in the Testgrid HYAML.
=> Support not providing iacProvider

infrastructure/src/main/resources/kubernetes_helmInfra.sh
**Purpose**
Check whether the Helm CLI is initialized by checking the existence of the Helm home directory. If not initialized, initialize with **helm init**.
Fixes #1296
=> Handle Helm initialisation

jenkins/slave-setup/ec2-slave-setup.sh
**Purpose**
Fixes #1298 
**Approach**
Change the remote location for downloading the MySQL connector jar.
=> Fix MySQL connector jar download link

jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
Identity server Integration tests are getting the following error.
```
org.apache.axis2.AxisFault: Too many open files
```
**Goals**
Fix the above error by increasing the file limit.
AWS
=> Increase the open file limit

jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
User limits were not set properly using the CloudFormation script as it needed to logout and login in order to apply the following. 
```
ulimit -n 65535
```
Therefore burned it to the AMI.
**Goals**
Fix the following error
```
INFO [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - Caused by: java.io.FileNotFoundException: /opt/testgrid/workspace/product-is/modules/integration/tests-integration/tests-backend/target/carbontmp1582014362976/wso2is-5.10.0-beta3-SNAPSHOT/repository/conf/bps.xml (Too many open files)
```
- Confirmed that this PR doesn't commit any keys, …
=> Burn user limits to the AMI

packer/resource-ami/config.sh
**Purpose**
User limits were not set properly using the CloudFormation script as it needed to logout and login in order to apply the following. 
```
ulimit -n 65535
```
Therefore should be burned to the AMI.
**Goals**
Fix the following error
```
INFO [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - Caused by: java.io.FileNotFoundException: /opt/testgrid/workspace/product-is/modules/integration/tests-integration/tests-backend/target/carbontmp1582014362976/wso2is-5.10.0-beta3-SNAPSHOT/repository/conf/bps.xml (Too many open files)
```
- Confirmed that this PR doesn't commit any keys, …
=> Change user limits in the Integration test EC2 instance

jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
Invoke the `cfn-signal` for RHEL based instances in TG so that the CFN stack creation completes successfully.
=> Invoke cfn-signal for RHEL based instances.

jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
Downgrade the EC2 instance type used for integration instance type. At the moment we are using a larger instance type with around 30GB memory.
=> Downgrade EC2 instance type used for integration test builds. 

jobs/test-resources/deploy.sh
**Purpose**
Resolves #1307 
The function "wait_for_server_startup" is unnecessary since the readiness check is already done with the cfn-signal when creating the stack. 
**Goals**
Remove function "wait_for_server_startup" in [1].
[1] https://raw.githubusercontent.com/wso2/testgrid/master/jobs/test-resources/deploy.sh
=> Remove function wait_for_server_startup

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java
**Purpose**
Fix if condition for OS selection
**Goals**
Fix the error with the TG agent not registering in Ubuntu nodes.
Ubuntu 18.04
AdoptOpenJDK 8
Maven 3.5.4
=> Fix if condtion for OS selection

jobs/intg-test-resources/infra.json
Fixing the error when starting up the server
Caused by: oracle.net.ns.NetException: Invalid connection string format, a valid format is: "//host[:port][/service_name]"
=> Updating SID in the URL

jobs/intg-test-resources/infra.json
Gives the following error without this validation query
java.sql.SQLException: Failed to validate a newly established connection.
=> Updating the validation query for oracle

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
> To support Temurin JDKs in Test Grid
=> Add CentOS AMI with support for Temurin JDK 8

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
Remove OracleJDK from allowd JDK values
Remove redundant JDK installing steps. ( we again do this in product_test_script) Fixes wso2-enterprise/wso2-apim-internal/issues/1908
=> Remove OracleJDK from integration tests

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
1. Adding CentOS AMI with APIM 4.2.0
2. Adding JDK 17 support
=> Add APIM 4.2.0 and JDK17

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
This PR adds the commands to install postgres15 client in CentOS in order to test PostgreSQL 15.3 in the testgrid.
=> Add commands to install postgres15 client in centos

jobs/intg-test-resources/update2-releases/wso2-update.sh
**Purpose**
This PR adds the update tool change to take the environment (live/staging/UAT) from an environment variable instead of the update config file  in the wso2-update.sh update script.
Related mail thread: "Changes to TestGrid build configurations"
=> Add the update tool change in the update script

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
This PR replaces the currently used python-pip package to python3-pip package since python-pip package is removed from Ubuntu 24.04.
=> Replace python-pip with python3-pip package

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
This PR adds the changes to support Ubuntu 24.04 by installing venv to install the aws-cfn-bootstrap package.
=> Add changes to support Ubuntu 24.04

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
This PR adds the script to install the following DB clients for the Ubuntu instance.
- MySQL
- PostgreSQL
- MariaDB
- MSSQL
=> Add script to install DB clients for Ubuntu

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
The existing oracle 19 DB engine version (oracle-se2_19.0.0.0.ru-2019-10.rur-2019-10.r1) seems to be discontinued by aws. Hence, bumping the oracle 19 DB engine version to oracle-se2_19.0.0.0.ru-2025-04.rur-2025-04.r1
=> Bump Oracle 19 DB Engine Version

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
Minor version bump from RHEL 9.5 to 9.6
**Approach**
- Run the following commands on top of `TestGrid-RHEL-9.3-APIM-2025-04-9`
```bash
sudo dnf clean all
sudo dnf update -y
```
- Create new ami: `TestGrid-RHEL-9.6-APIM-2025-09-10`
=> Update RHEL version to 9.6
