wso2/testgrid

.gitignore
Added `.idea/` directory to git ignore
=> Add idea files to git ignore

issue_template.md, pull_request_template.md
=> Add pull request template and issue template

reporting/src/main/java/org/wso2/carbon/testgrid/reporting/TestReportEngine.java
=> Fix path traversal logic when producing reports

reporting/src/main/java/org/wso2/carbon/testgrid/reporting/reader/CSVResultReader.java, reporting/src/main/java/org/wso2/carbon/testgrid/reporting/renderer/MustacheTemplateRenderer.java, reporting/src/main/java/org/wso2/carbon/testgrid/reporting/util/FileUtil.java
Remove log entries from reporting module
=> Remove log entries from reporting module

bin/testgrid.sh, core/src/main/java/org/wso2/carbon/testgrid/core/Main.java, core/src/main/java/org/wso2/carbon/testgrid/core/TestPlanExecutor.java, deployment/src/main/java/org/wso2/carbon/testgrid/deployment/DeployerService.java, infrastructure/src/main/java/org/wso2/carbon/testgrid/infrastructure/InfrastructureProviderService.java
Resolves #15 
A Shell script that initiates TestGrid with user input.
A User should be able to select the product and its version to initiate TestGrid.
Ubuntu ,  JDK 8
=> CLI for TestGrid

reporting/src/main/resources/templates/product_template.mustache, reporting/src/main/resources/templates/scenario_template.mustache
Fix rendering issues in templates
=> Fix rendering issues in templates

reporting/src/main/java/org/wso2/carbon/testgrid/reporting/TestReportEngine.java, reporting/src/main/java/org/wso2/carbon/testgrid/reporting/model/TestPlanReport.java, reporting/src/main/resources/templates/html_template.mustache, reporting/src/main/resources/templates/product_template.mustache, reporting/src/main/resources/templates/scenario_template.mustache, reporting/src/test/java/org/wso2/carbon/testgrid/reporting/TestReportEngineTest.java
Resolves #21
* Include test plan details in test report template
Test plan details should be visible to the end user
* Test plan details included in report
=> Include test plan details in test report template

reporting/src/main/java/org/wso2/carbon/testgrid/reporting/TestReportEngineImpl.java, reporting/src/main/java/org/wso2/carbon/testgrid/reporting/reader/ResultReaderFactory.java, reporting/src/main/java/org/wso2/carbon/testgrid/reporting/result/TestResultBeanFactory.java
Resolves #49 
* Fix test report generation issues for TestNG
* Fix test report generation issues for TestNG
- Unit tests 
> Will be tracked via https://github.com/wso2-incubator/wso2-test-grid/issues/50
> Will be tracked via https://github.com/wso2-incubator/wso2-test-grid/issues/50
=> Fix test report generation errors

common/src/main/java/org/wso2/carbon/testgrid/common/InfrastructureProvider.java, core/src/main/java/org/wso2/carbon/testgrid/core/TestPlanExecutor.java, core/src/test/java/org/wso2/carbon/testgrid/core/ScenarioExecutorTest.java, core/src/test/java/org/wso2/carbon/testgrid/core/TestGridMgtServiceTest.java
> Resolves #58.
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> #56 , #28
=>  Change the method signature of removeInfrastructure accept Infrastructure object

common/src/main/java/org/wso2/carbon/testgrid/common/DeployerService.java, common/src/main/java/org/wso2/carbon/testgrid/common/Deployment.java, common/src/main/java/org/wso2/carbon/testgrid/common/InfrastructureProvider.java, common/src/main/java/org/wso2/carbon/testgrid/common/TestAutomationEngine.java, common/src/main/java/org/wso2/carbon/testgrid/common/TestPlan.java, core/src/main/java/org/wso2/carbon/testgrid/core/ScenarioExecutor.java, core/src/main/java/org/wso2/carbon/testgrid/core/TestGridMgtService.java, core/src/main/java/org/wso2/carbon/testgrid/core/TestPlanExecutor.java
> To resolve #71 
> This PR is to fix the minor issues in java-doc comments in TestGrid core and common components.
=> Fix java-doc issues in common and core components

automation/pom.xml, automation/src/main/java/org/wso2/carbon/testgrid/automation/executers/JMeterExecuter.java, infrastructure/pom.xml, infrastructure/src/main/java/org/wso2/carbon/testgrid/infrastructure/aws/AWSManager.java, pom.xml
This PR fully remove the TestGrid Utils dependency from the build.
=> Remove utils dependency

distribution/assembly.xml
=> Fixing issue #76 - testgrid.sh should have execute permission #76

common/src/main/java/org/wso2/testgrid/common/AbstractUUIDEntity.java, common/src/main/java/org/wso2/testgrid/common/TestScenario.java, core/src/main/java/org/wso2/testgrid/core/ScenarioExecutor.java, core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java, dao/src/main/java/org/wso2/testgrid/dao/repository/AbstractRepository.java, dao/src/main/java/org/wso2/testgrid/dao/repository/DatabaseRepository.java, dao/src/main/java/org/wso2/testgrid/dao/repository/InfraCombinationRepository.java, dao/src/main/java/org/wso2/testgrid/dao/repository/InfraResultRespository.java, dao/src/main/java/org/wso2/testgrid/dao/repository/OperatingSystemRepository.java, dao/src/main/java/org/wso2/testgrid/dao/repository/ProductTestPlanRepository.java, dao/src/main/java/org/wso2/testgrid/dao/repository/TestCaseRepository.java, dao/src/main/java/org/wso2/testgrid/dao/repository/TestPlanRepository.java, dao/src/main/java/org/wso2/testgrid/dao/repository/TestScenarioRepository.java, dao/src/main/java/org/wso2/testgrid/dao/uow/TestScenarioUOW.java
Resolves #129
* Fix persist TestScenario on the fly
* Fix persist TestScenario on the fly
=> Fix persist TestScenario on the fly

automation/src/test/java/org/wso2/testgrid/automation/executor/JMeterExecutorTest.java
Test failure fix. 
Posix specific logic is not platform independent. Hence, this may fail in other environments.
=> fixing test failures. Posix specific logic is not platform independent.

automation/src/test/java/org/wso2/testgrid/automation/executor/JMeterExecutorTest.java
=> fixing build errors

common/src/main/java/org/wso2/testgrid/common/TestPlan.java, dao/src/main/java/org/wso2/testgrid/dao/uow/TestAutomationUOW.java, dao/src/main/java/org/wso2/testgrid/dao/uow/WebAppUOW.java, dao/src/main/resources/META-INF/persistence.xml
Implement DAO API to feature database transactions in the web app
Resolves #141
* Implement DAO API to feature database transactions in the web app
* Implement DAO API to feature database transactions in the web app
=> Implement DAO API to feature database transactions

automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterExecutor.java, automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterResultCollector.java, automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterTestListener.java, dao/src/main/java/org/wso2/testgrid/dao/uow/TestAutomationUOW.java, dao/src/main/resources/META-INF/persistence.xml
Resolves #143
* Fix test case status not persisted after test
* Fix test case status not persisted after test
=> Fix test case status not persisted after test

common/src/main/java/org/wso2/testgrid/common/AbstractUUIDEntity.java, common/src/main/java/org/wso2/testgrid/common/Database.java, dao/pom.xml, dao/src/main/java/org/wso2/testgrid/dao/repository/AbstractRepository.java, dao/src/main/java/org/wso2/testgrid/dao/util/DAOUtil.java, dao/src/test/java/org/wso2/testgrid/dao/repository/DatabaseRepositoryTest.java, pom.xml
Adds unit tests for DatabaseRepository (issue: 113)
* Add unit tests for database repository.
* Add unit tests for database repository.
- Unit tests 
|        Class       | Class coverage | Method coverage | Line coverage |
|:------------------:|:--------------:|:---------------:|:-------------:|
| AbstractRepository |   100% (1/1)   |    87% (7/8)    |  80% (51/63)  |
| DatabaseRepository |   100% (1/1)   |    100% (6/6)   |   100% (8/8)  |
* https://github.com/wso2-incubator/wso2-test-grid/pull/142
=> Add unit tests for DatabaseRepository

api/src/main/java/org/wso2/testgrid/bean/TestPlan.java
=> Add jdk, db, os to org.wso2.testgrid.api.TestPlan

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/aws/AWSManager.java
Resolves #165 
> Change logic to use output variables as it is.
> Remove replace logic.
=> Change host name logic

dao/pom.xml, pom.xml
Resolves #162
* Fix the java.lang.SecurityException thrown when running the TestGrid webapp inside tomcat server
* Fix the java.lang.SecurityException thrown when running the TestGrid webapp inside tomcat server
=> Fix the java.lang.SecurityException thrown in TestGrid

web/src/main/webapp/js/functions.js
=> Fix wrong api json keys and empty json objects

core/src/main/java/org/wso2/testgrid/core/TestGridUtil.java
Refactored the code to use Paths and Files API
=> Refector code - use Paths and Files API

dao/src/main/java/org/wso2/testgrid/dao/uow/WebAppUOW.java
> Resolve #172 .
> Changed methods to search using model object instead of string id.
=> Fix issues with data access

web/src/main/webapp/index.html, web/src/main/webapp/js/functions.js
Resolves #174 
Display the date in a standard format
=> Fix unreadable date format in web app UI

web/src/main/webapp/js/functions.js
Resolves #176 
This fixes wrong attributes given to html elements in functions.js which area used to make the REST API calls.
=> Fix test scenarios not being displayed issue in the web app UI

web/src/main/webapp/css/styles.css, web/src/main/webapp/index.html, web/src/main/webapp/js/functions.js
Resolves #178 
The appearance and the table structure of UI of the web app is improved.
=> Improve web app UI

core/src/main/java/org/wso2/testgrid/core/TestGridMgtServiceImpl.java, core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java, dao/src/main/java/org/wso2/testgrid/dao/uow/TestPlanUOW.java
=> Fix issue with persisting TestPlans

dao/src/main/java/org/wso2/testgrid/dao/uow/ReportGenerationUOW.java
Resolves #186
* Fix report generation to happen for latest product test plan
=> Fix report generation to happen for latest product test plan

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/aws/AWSManager.java
> To resolve issues with postgres RDS template.
=> Fix postgres sql instance creation issue

jenkins-pipelines/Jenkinsfile
Update Jenkins pipeline plugin flow
=> Update jenkins pipleline plugin flow

core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java, dao/pom.xml, dao/src/main/java/org/wso2/testgrid/dao/SortOrder.java, dao/src/main/java/org/wso2/testgrid/dao/repository/AbstractRepository.java, dao/src/main/java/org/wso2/testgrid/dao/repository/DatabaseRepository.java, dao/src/main/java/org/wso2/testgrid/dao/repository/InfraCombinationRepository.java, dao/src/main/java/org/wso2/testgrid/dao/repository/InfraResultRespository.java, dao/src/main/java/org/wso2/testgrid/dao/repository/OperatingSystemRepository.java, dao/src/main/java/org/wso2/testgrid/dao/repository/ProductTestPlanRepository.java, dao/src/main/java/org/wso2/testgrid/dao/repository/TestCaseRepository.java, dao/src/main/java/org/wso2/testgrid/dao/repository/TestPlanRepository.java, dao/src/main/java/org/wso2/testgrid/dao/repository/TestScenarioRepository.java, dao/src/main/java/org/wso2/testgrid/dao/uow/ReportGenerationUOW.java, dao/src/main/java/org/wso2/testgrid/dao/uow/TestPlanUOW.java, dao/src/test/java/org/wso2/testgrid/dao/repository/DatabaseRepositoryTest.java, jenkins-pipelines/Jenkinsfile, pom.xml, reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngineImpl.java
Resolves #196 
* Add ordering methods for the DAO layer
=> Add ordering methods for the DAO layer

common/src/main/java/org/wso2/testgrid/common/InfraCombination.java, common/src/main/java/org/wso2/testgrid/common/InfraResult.java, common/src/main/java/org/wso2/testgrid/common/OperatingSystem.java, common/src/main/java/org/wso2/testgrid/common/ProductTestPlan.java, common/src/main/java/org/wso2/testgrid/common/TestCase.java, common/src/main/java/org/wso2/testgrid/common/TestPlan.java, common/src/main/java/org/wso2/testgrid/common/TestScenario.java
Resolves #200 
* Fix IllegalArgumentException when getting records
=> Fix IllegalArgumentException when getting records

common/src/main/java/org/wso2/testgrid/common/TestPlan.java
=> Fix deployment pattern default value java.sql.SQLException

deployment/src/main/java/org/wso2/testgrid/deployment/deployers/AWSDeployer.java
Resolves #210 
Server startup wait is increased to 60 minutes
=> Increase server startup waiting time

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/aws/AWSManager.java
Resolves #213 
AWS Cloudformation parameter JSON usage is removed.
All the parameters can be passed from the infrastructure yaml config file. because of that there is no need for a separate JSON file.
Removed the JSON reading logic from the code.
=> Remove parameter JSON usage

common/src/main/java/org/wso2/testgrid/common/Script.java, common/src/main/java/org/wso2/testgrid/common/util/LambdaExceptionUtils.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/aws/AWSManager.java, infrastructure/src/test/java/org/wso2/testgrid/infrastructure/AWSManagerTest.java
Resolves #215 
Credential details can be stored as environment variables and referred via this section.
Add a new section to the infra.yaml file to list the parameters
=> Add Environment Variable parameter list for CF

automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterExecutor.java
> Resolves #219 .
Trim extra spaces before executing the jmx file.
=> Add parameter trim to JmeterExecutor

automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterExecutor.java, automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterResultCollector.java, automation/src/main/java/org/wso2/testgrid/automation/executor/TestExecutorFactory.java, common/src/main/java/org/wso2/testgrid/common/Database.java, common/src/main/java/org/wso2/testgrid/common/InfraCombination.java, common/src/main/java/org/wso2/testgrid/common/InfraResult.java, common/src/main/java/org/wso2/testgrid/common/OperatingSystem.java, common/src/main/java/org/wso2/testgrid/common/ProductTestPlan.java, common/src/main/java/org/wso2/testgrid/common/TestCase.java, common/src/main/java/org/wso2/testgrid/common/TestPlan.java, common/src/main/java/org/wso2/testgrid/common/TestScenario.java, common/src/main/java/org/wso2/testgrid/common/util/StringUtil.java, core/src/main/java/org/wso2/testgrid/core/ScenarioExecutor.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateInfraPlanCommand.java, core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java, dao/src/main/java/org/wso2/testgrid/dao/repository/AbstractRepository.java, dao/src/main/java/org/wso2/testgrid/dao/uow/InfraCombinationUOW.java, dao/src/test/resources/testng.xml, reporting/src/main/java/org/wso2/testgrid/reporting/model/TestPlanView.java
Resolves #223 
Resolves #224 
* Fix Stackoverflow exceptions on toString() method invocation
* Added more information to JMeter message
=> Make JMeter failure message descriptive

automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterResultCollector.java, dao/src/main/java/org/wso2/testgrid/dao/EntityManagerHelper.java, dao/src/main/java/org/wso2/testgrid/dao/repository/AbstractRepository.java, dao/src/main/java/org/wso2/testgrid/dao/repository/DatabaseRepository.java, dao/src/main/java/org/wso2/testgrid/dao/repository/InfraCombinationRepository.java, dao/src/main/java/org/wso2/testgrid/dao/repository/InfraResultRespository.java, dao/src/main/java/org/wso2/testgrid/dao/repository/OperatingSystemRepository.java, dao/src/main/java/org/wso2/testgrid/dao/repository/ProductTestPlanRepository.java, dao/src/main/java/org/wso2/testgrid/dao/repository/TestCaseRepository.java, dao/src/main/java/org/wso2/testgrid/dao/repository/TestPlanRepository.java, dao/src/main/java/org/wso2/testgrid/dao/repository/TestScenarioRepository.java, dao/src/main/java/org/wso2/testgrid/dao/uow/InfraCombinationUOW.java, dao/src/main/java/org/wso2/testgrid/dao/uow/ProductTestPlanUOW.java, dao/src/main/java/org/wso2/testgrid/dao/uow/TestCaseUOW.java, dao/src/main/java/org/wso2/testgrid/dao/uow/TestPlanUOW.java, dao/src/main/java/org/wso2/testgrid/dao/uow/TestScenarioUOW.java, dao/src/main/resources/META-INF/persistence.xml, dao/src/test/java/org/wso2/testgrid/dao/repository/DatabaseRepositoryTest.java, dao/src/test/java/org/wso2/testgrid/dao/repository/ProductTestPlanRepositoryTest.java, dao/src/test/resources/META-INF/persistence.xml, dao/src/test/resources/testng.xml
Fix unit test failure in DatabaseRepository
Resolves #226 
* Fix build failure due to test failures in DAO module
=> Fix test fail in Database Repository

dao/src/main/java/org/wso2/testgrid/dao/EntityManagerHelper.java
Resolves #227 
This PR is related to PR #227
=> Fix nullpointer exception when executing JMeter

web/pom.xml
Fixes the issue of missing logging dependency in the Testgrid REST API.
Resolves #236
=> Fix missing logging dependency in web module

reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngine.java
Fixed report missing out certain summary information
Resolves #229 
* Fixed report missing out certain summary information
* #239
=> Fix report missing out summary information

reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngine.java, reporting/src/main/java/org/wso2/testgrid/reporting/model/GroupBy.java, reporting/src/main/java/org/wso2/testgrid/reporting/model/ReportElement.java, reporting/src/main/resources/templates/group_by.mustache, reporting/src/main/resources/templates/per_axis_header.mustache, reporting/src/main/resources/templates/report.mustache, reporting/src/main/resources/templates/report_element.mustache
Fix issues in report generation
Resolves #229 
* Fix issues in report generation
* #239 
* #240
=> Fix issues in report generation

dao/src/main/java/org/wso2/testgrid/dao/uow/TestPlanUOW.java, dao/src/main/java/org/wso2/testgrid/dao/uow/TestScenarioUOW.java
Adds UOW classes for TestPlan and TestScenario
=> Add UOWs for TestPlan and TestScenario

core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java, core/src/test/resources/generated-test-config.yaml
* Fix get test config from generated YAML
=> Fix get test config from generated YAML

core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java, core/src/main/java/org/wso2/testgrid/core/config/InputTestConfig.java
* Fix issues in test plan YAML file generation
#254
=> Fix issue in test plan generation

core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java, core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java
* Fix issue in writing YAML test plans
=> Fix issue in writing YAML test plans

core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java, core/src/main/java/org/wso2/testgrid/core/config/TestConfig.java
* Fix issue in reading YAML test plans
=> Fix issue in reading YAML test plans

common/src/main/java/org/wso2/testgrid/common/Infrastructure.java, core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java, core/src/main/resources/single-node-infra.yaml, core/src/test/resources/test-config.yaml, dao/src/main/java/org/wso2/testgrid/dao/repository/DeploymentRepository.java, dao/src/main/java/org/wso2/testgrid/dao/uow/DeploymentPatternUOW.java, infrastructure/pom.xml, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/aws/AWSManager.java
> Fix run test plan flow partially
=> Fix run test plan flow

automation/src/main/java/org/wso2/testgrid/automation/reader/TestReaderFactory.java, common/src/main/java/org/wso2/testgrid/common/TestPlan.java, core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java, core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java, dao/src/main/java/org/wso2/testgrid/dao/repository/ProductRepository.java, dao/src/main/java/org/wso2/testgrid/dao/uow/DeploymentPatternUOW.java, dao/src/main/java/org/wso2/testgrid/dao/uow/ProductUOW.java, dao/src/main/java/org/wso2/testgrid/dao/uow/TestPlanUOW.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/aws/AWSManager.java
>  Fix errors in test execution flow
=> Revise test execution flow

core/src/main/java/org/wso2/testgrid/core/ScenarioExecutor.java, core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java
> Fixes the persistence logic causing duplication of deployment pattern in the database.
=> Fix duplication of deployment pattern records in the database

core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java, core/src/main/resources/single-node-infra.yaml, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/aws/AWSManager.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java
> This will fix the infrastructure parameter passing for AWS Cloudformation scrips.
=> Fix runtestplan infra paramaters

core/src/main/java/org/wso2/testgrid/core/ScenarioExecutor.java, core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java, dao/src/main/java/org/wso2/testgrid/dao/repository/TestCaseRepository.java, dao/src/main/java/org/wso2/testgrid/dao/repository/TestScenarioRepository.java, dao/src/main/java/org/wso2/testgrid/dao/uow/TestCaseUOW.java, dao/src/main/java/org/wso2/testgrid/dao/uow/TestScenarioUOW.java
> The final status of the scenario should depend on the execution result of its test cases and the final status of the test plan should depend on its scenarios.
=> Implement setting final statuses

automation/src/main/java/org/wso2/testgrid/automation/reader/TestReaderFactory.java, core/src/main/java/org/wso2/testgrid/core/ScenarioExecutor.java, core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java, core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java, dao/src/main/java/org/wso2/testgrid/dao/uow/DeploymentPatternUOW.java, dao/src/main/java/org/wso2/testgrid/dao/uow/TestCaseUOW.java, dao/src/main/java/org/wso2/testgrid/dao/uow/TestScenarioUOW.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/aws/AWSManager.java
> Fix test running issues, FindBugs and CheckStyle issues
=> Fix issues with test running

common/src/main/java/org/wso2/testgrid/common/DeploymentPattern.java, common/src/main/java/org/wso2/testgrid/common/DeploymentPatternTestFailureStat.java, common/src/main/java/org/wso2/testgrid/common/Product.java, common/src/main/java/org/wso2/testgrid/common/ProductTestStatus.java, dao/src/main/java/org/wso2/testgrid/dao/repository/DeploymentPatternRepository.java, dao/src/main/java/org/wso2/testgrid/dao/repository/ProductRepository.java, dao/src/main/java/org/wso2/testgrid/dao/repository/TestPlanRepository.java, web/src/main/java/org/wso2/testgrid/web/api/APIUtil.java, web/src/main/java/org/wso2/testgrid/web/api/DeploymentPatternService.java, web/src/main/java/org/wso2/testgrid/web/api/ProductService.java, web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java, web/src/main/java/org/wso2/testgrid/web/api/TestScenarioService.java, web/src/main/java/org/wso2/testgrid/web/bean/TestCase.java
> To resolve JPA issues in #268
> #268
=> Fix JPA queries

web/src/main/java/org/wso2/testgrid/web/api/DeploymentPatternService.java, web/src/main/java/org/wso2/testgrid/web/api/ProductService.java, web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java
> Change date-time conversion formats.
> #268
=> Change date format in REST APIs

common/src/main/java/org/wso2/testgrid/common/DeploymentPatternTestFailureStat.java, dao/src/main/java/org/wso2/testgrid/dao/repository/DeploymentPatternRepository.java, dao/src/main/java/org/wso2/testgrid/dao/repository/TestPlanRepository.java, web/src/main/java/org/wso2/testgrid/web/api/APIUtil.java
> Fix failure test cases data retrive issue
> #268
=> Fix failure test case issue

README.md
=> Feature list doc

jenkins-pipelines/continuous-delivery/Jenkinsfile
Set correct job name of testgrid main job in CD Jenkinsfile
https://wso2.org/jenkins/job/testgrid/job/testgrid
=> Set correct job name of testgrid main job in CD Jenkinsfile

common/pom.xml, common/src/main/java/org/wso2/testgrid/common/TestPlan.java, common/src/main/java/org/wso2/testgrid/common/exception/TestGridLoggingException.java, common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java, core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateReportCommand.java, core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java, dao/src/main/java/org/wso2/testgrid/dao/uow/TestScenarioUOW.java, pom.xml, reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngine.java
Test reports for each test plan will now be created in the relevant test artefacts location
Resolves #306 
* Save test reports for each test run in the test run artefacts location
=> Generate test report for each test run in test artifact directory

CHANGE_LOG.md
For each fix we do, and design changes we introduce, there must be a github issue. This github issue along with a brief description need to go into the changelog file.
Fixes #269
=> Adds CHANGELOG file to capture changes done in each release.

common/src/main/java/org/wso2/testgrid/common/ShellExecutor.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/ShellScriptProvider.java
This PR fixes: https://github.com/wso2-incubator/testgrid/issues/212
To support shell execution in testgrid. 
A sample test-config.yaml is as follows
```
productName: "IS"
productVersion: "5.4.0"
channel: "LTS"
deploymentPatterns:
-  "pattern-2"
infraParams:
- osName: "Ubuntu"
osVersion:
- "16.04"
databaseName: "MYSQL"
databaseVersion:
- "5.7"
jdk:
- "ORACLE_JDK8"
scenarios:
-  "solution01"
infrastructure:
providerType: "AWS"
clusterType: "None"
instanceType: "EC2"
name: "pattern-2"
securityProperties:
apiKey: "242424"
sshKey: "abc.key"
scripts:
- scriptType: "INFRA_CREATE"
filePath: "infra-provision.sh"
name: "provision"
environmentScriptParameters:
scriptParameters:
- scriptType: "INFRA_DESTROY"
filePath: "infra-destroy.sh"
name: "destroy"
environmentScriptParameters:
scriptParameters: …
```
=> Fix and improve Shell execution flow

common/src/main/java/org/wso2/testgrid/common/ShellExecutor.java
Fix thread hanging issue in shell executor.
Resolves #359
=> Fix thread hanging issue in shell executor

common/src/main/java/org/wso2/testgrid/common/Infrastructure.java, common/src/main/java/org/wso2/testgrid/common/Script.java, common/src/main/java/org/wso2/testgrid/common/TestPlan.java, core/src/main/java/org/wso2/testgrid/core/ScenarioExecutor.java, core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java, core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java, deployment/src/main/java/org/wso2/testgrid/deployment/deployers/ShellDeployer.java, deployment/src/main/resources/META-INF/services/org.wso2.testgrid.common.DeployerService, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/ShellScriptProvider.java, test-scripts/local-is-deployment/DeploymentPatterns/pattern-2/deploy.sh, test-scripts/local-is-deployment/DeploymentPatterns/pattern-2/infra-provision.sh, test-scripts/local-is-deployment/README.md, test-scripts/local-is-deployment/test-config.yaml
This PR adds support for execution of deploy.sh script. And it resolves following issues.
Resolves #342 
Resolves #336
A sample test-config.xml is as follows,
```
################################################################################
#
#
#
################################################################################
productName: "IS"
productVersion: "5.4.0"
channel: "LTS"
deploymentPatterns:
-  "pattern-2"
infraParams:
- osName: "Ubuntu"
osVersion:
- "16.04"
databaseName: "H2"
databaseVersion:
- "5.7"
jdk:
- "ORACLE_JDK8"
scenarios:
-  "solution01"
infrastructure:
providerType: "SHELL"
clusterType: "None"
instanceType: "None"
name: "pattern-2"
securityProperties:
apiKey: "242424"
sshKey: "abc.key"
scripts:
- scriptType: "INFRA_CREATE"
filePath: "infra-provision.sh"
name: …
```
=> Add deploy script execution support

web/src/main/java/org/wso2/testgrid/web/utils/ConfigurationContext.java, web/src/main/java/org/wso2/testgrid/web/utils/Constants.java, web/src/main/webapp/WEB-INF/classes/testgrid-web-config.properties
Currently testgrid-web-config property file exists inside the webapp. But it has to be moved outside the webapp.
Fixes #367
=> Move testgrid-web-config property file location to outside of the webapp.

web/src/main/webapp/WEB-INF/web.xml
Update web.xml to facilitate HTTP redirection.
=> Update web.xml to facilitate HTTP redirection

web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java, web/src/main/react-dashboard/src/components/DeploymentPatternView.js, web/src/main/react-dashboard/src/components/TestRunView.js
Resolves #382
Fix undefined error when navigating to test log view in web app
* Fixed undefined error when navigating to test log view in web app
* https://github.com/wso2/testgrid/pull/360
=> Fix undefined error when loading test log view

web/src/main/react-dashboard/src/components/TestRunView.js
Fix error on parsing success percentage due to being "NaN"
This PR is an addition to https://github.com/wso2/testgrid/pull/383
* Fix error on parsing success percentage
* https://github.com/wso2/testgrid/pull/383
=> Fix error on parsing success percentage

common/src/main/java/org/wso2/testgrid/common/Product.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateReportCommand.java, core/src/test/resources/test-config.yaml, reporting/src/main/resources/templates/report.mustache, web/src/main/java/org/wso2/testgrid/web/api/ProductService.java, web/src/main/react-dashboard/src/components/TestRunView.js
Resolves #386 
* Pending removal of product version and product channel
* TestGrid Logging dashboard displaying empty tables when no records
=> Code refactor

web/src/main/java/org/wso2/testgrid/web/api/APIUtil.java, web/src/main/react-dashboard/src/App.js, web/src/main/react-dashboard/src/components/DeploymentPatternView.js, web/src/main/react-dashboard/src/components/ProductStatusView.js, web/src/main/react-dashboard/src/components/SingleRecord.js
Resolves #395 
Resolves #391
Fix dashboard issues that arise when the database results are empty for queries
Fix broken admin URL
API returns null value when there are no records and dashboard handles those null values appropriately
=> Fix dashboard issues

distribution/bin/testgrid, jenkins-pipelines/Jenkinsfile
Update mysql driver URL in Jenkins pipeline.
This is related to : https://github.com/wso2/testgrid/pull/399
=> Update mysql driver URL in Jenkins pipeline

core/src/main/java/org/wso2/testgrid/core/command/HelpCommand.java
Update help command output.
Resolves #390
=> Update help command output

core/src/main/java/org/wso2/testgrid/core/command/HelpCommand.java
Fix check style issue.
Related to #402
=>  Fix check style issue

distribution/assembly.xml
Update the WAR name is assembly.xml
This is part of #403
=> Update the WAR name is assembly.xml

pom.xml, web/pom.xml, web/src/main/java/org/wso2/testgrid/web/api/LogEventSocketMediator.java, web/src/main/java/org/wso2/testgrid/web/utils/FileWatcher.java, web/src/main/java/org/wso2/testgrid/web/utils/FileWatcherException.java, web/src/main/react-dashboard/package.json, web/src/main/react-dashboard/src/components/TestRunView.js
Resolves #361
Add live log view capability when on pending state
* Added live log view capability when on pending state
=> Add live log view capability when on pending state

distribution/bin/testgrid
=> Fix debug issue in testgrid executable script

automation/pom.xml, core/src/main/java/org/wso2/testgrid/core/ScenarioExecutor.java, jenkins-pipelines/Jenkinsfile, pom.xml
=> Fix scenario execution failures

common/src/main/java/org/wso2/testgrid/common/infrastructure/InfrastructureParameter.java
Adding DATABASE infrastructure parameter back since it is required for the current functionality. 
Stabilize the distribution.
=> adding DATABASE infrastructure parameter back. Fixes #439

web/src/main/react-dashboard/src/components/DeploymentPatternView.js
Resolves #442 
Fix the product name variable 
Use the saved product name value.
=> Fix product name in deployment pattern view

dao/src/main/java/org/wso2/testgrid/dao/repository/AbstractRepository.java
> Includes the fix for wrong logic in findByFields method in AbstractRepository. Fixes the wrong grouping shown on the dashboard.
> Resolves #445
> Allow searching the database using multiple params with and criteria when persisting records to the database. 
=> Fix findByFields method to use AND condition for search criteria

docs/Infrastructure-Deployment-Scenarios-Repository-Structure.md
Setting proper title for doc: Infrastructure / Deployment / and Scenarios Repository Structure - External consumers' view
=> Setting proper title for doc: Infrastructure / Deployment / and Scenarios Repository Structure - External consumers' view

docs/Infrastructure-Deployment-Scenarios-Repository-Structure.md
Update with 'Deploy config value sets' description in Infrastructure-Deployment-Scenarios-Repository-Structure.md
=> Update with 'Deploy config value sets' description

docs/Infrastructure-Deployment-Scenarios-Repository-Structure.md
fixes for Infrastructure-Deployment-Scenarios-Repository-Structure.md with
-updated with exact script name: config.sh
-corrected file reference for init.sh
=> Update Infrastructure-Deployment-Scenarios-Repository-Structure.md with script names

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/aws/AWSManager.java
Use stack ID instead of stack name for describing stacks.
Fixes #469.
Using the stackId is the only guaranteed way to make sure we get the stack that actually belong to this particular test-run.
=> Use stack ID instead of stack name for describing stacks

automation/src/main/java/org/wso2/testgrid/automation/executor/TestNgExecutor.java, automation/src/main/java/org/wso2/testgrid/automation/reader/JMeterTestReader.java
> Removes usage of string concatenation for locations and rewrite using java.nio.file.Paths
> Resolves #53 
=> Rewrite retrieving locations using java.nio.file.Paths

automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterResultCollector.java
=> Fix failing persistence for long failure massages in test cases

core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java, core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java, deployment/src/main/java/org/wso2/testgrid/deployment/deployers/AWSDeployer.java, deployment/src/main/java/org/wso2/testgrid/deployment/deployers/ShellDeployer.java
Fix build failure due to missing DeploymentPatternConfig class
=> Fix build failure due to missing DeploymentPatternConfig class

common/src/main/java/org/wso2/testgrid/common/InfrastructureProvider.java, common/src/main/java/org/wso2/testgrid/common/InfrastructureProvisionResult.java, common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java, core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java, core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java, deployment/src/main/java/org/wso2/testgrid/deployment/deployers/ShellDeployer.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/OpenStackProvider.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/ShellScriptProvider.java, infrastructure/src/test/java/org/wso2/testgrid/infrastructure/AWSProviderTest.java
Resolves  #506 
This PR adds the changes to support the parameter passing to shell scripts.
Goal is to pass the parameters from the testgrid.yaml file to the shell scripts.
=> Refine shell script execution

distribution/bin/log4j2.xml
Reduce verbosity in testgrid console output
Reduce verbosity in testgrid console output
=> Reduce verbosity in testgrid console output

pom.xml
**Purpose**
Fix build failure
Resolves #568
**Goals**
Fix build failure
**Approach**
Changing the artifact version to latest
=> Fix build failure caused by the older version of an artifact

pom.xml
=> Revert "Fix build failure caused by the older version of an artifact"

common/src/main/java/org/wso2/testgrid/common/TestGridConstants.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java, core/src/test/java/org/wso2/testgrid/core/command/GenerateTestPlanCommandTest.java, core/src/test/java/org/wso2/testgrid/core/command/RunTestPlanCommandTest.java
**Purpose**
Add new "jobs" directory to Test-plan persisting location.
```
Previous location: <TestGrid Home><PRODUCT>/test-plans
New location will be: <TestGrid Home>/jobs/<PRODUCT>/test-plans
```
Relates to #526 
Updated.
=> Move test-plans to "<TestGrid Home>/jobs/<PRODUCT>/test-plans" directory.

automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterResultCollector.java
**Purpose**
Contains changes related to making the test case failure message simpler
Resolves #490
**Goals**
Make the final report and dashboard more readable.
**Approach**
Rework JMeterResultCollector#sampleOccured
=> Make testcase failure message simple

automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterResultCollector.java
**Purpose**
To fix the build issue caused by PR #584
#584
=> Fix build issue due to unused imports

automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterResultCollector.java
**Purpose**
Fixes the build failure by removing unused imports
=>  Remove unused imports

automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterExecutor.java, common/src/main/java/org/wso2/testgrid/common/Status.java, core/src/main/java/org/wso2/testgrid/core/ScenarioExecutor.java, core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java, core/src/main/java/org/wso2/testgrid/core/command/CommandHandler.java, core/src/main/java/org/wso2/testgrid/core/command/HelpCommand.java, core/src/main/java/org/wso2/testgrid/core/command/ResolveStatusesCommand.java, core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java
**Purpose**
Introduces ResolveStatusesCommand and contains changes related to setting proper statuses for test-plans and test scenarios.
Resolves #581 
**Goals**
Rework invalid statuses and make them more accurate.
=> Improve states and introduce ResolveStatusesCommand

core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java
**Purpose**
Contains changes related to fixing the test failure
**Goals**
Fix test failure to make the build stable
**Approach**
=> Fix test failure in testgrid core

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/aws/AMIMapper.java
=> Remove JDK from AMI lookup parameters

deployment/src/main/java/org/wso2/testgrid/deployment/deployers/ShellDeployer.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java
**Purpose**
Contains changes related to modifying the deployers to consume the newly created tomcat instance.
Resolves #630
=> Change tomcat host details

README.md, docs/QuickStartGuide.md
**Purpose**
Adds a quick start guide to docs.
Resolves #631 
**Goals**
To provide an end-to-end quick start guide with steps for running TestGrid.
=> Document quick start guide for running testgrid

jenkins/pipelines/test-jobs/wso2is5.4.0LTS/Jenkinsfile
**Purpose**
To resolve #640 
N/A
=> Fix path issues in wso2is5.4.0LTS build

jenkins/pipelines/test-jobs/wso2is5.4.1LTS/Jenkinsfile
=> Add wso2is5.4.1LTS build file to the repo

core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java
**Purpose**
Contains changes related to fixing the scenario duplication.
Resolves #655
**Goals**
Fix duplication of scenarios
**Approach**
Rework TestPlanExecutor#runScenarioTests.
=> Fix duplicated test scenarios

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java
**Purpose**
Contains changes related to logging the infrastructure details of the stack being created to the console and log files.
Resolves #663 
**Goals**
Enable viewing infrastructure information from the logs.
**Approach**
Modify AWSProvider#doProvision
=> Log infrastructure parameters to the console

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java
=> Fix AWS stack delete callback issue

jenkins/pipelines/test-jobs/wso2apim-2.1.0-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2ei-6.1.1-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2is-5.5.0-LTS/Jenkinsfile
=> Add updated jenkins pipeline scripts for product jobs

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java
**Purpose**
Update the tomcat host.
=> Add new tomcat details

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java
**Purpose**
To update tomcat host
=> Change tomcat host

jenkins/pipelines/test-jobs/wso2apim-2.2.0-LTS/Jenkinsfile
**Purpose**
Contains the Jenkins pipeline script of APIM 2.2.0.
Resolves #677 
=> Add APIM 2.2.0 Jenkins pipeline script

jenkins/pipelines/test-jobs/wso2is-5.3.0-LTS/Jenkinsfile
**Purpose**
Contains the Jenkins pipeline script of IS 5.3.0.
Resolves #675 
**Samples**
=> Add IS-5.3.0 Jenkins pipeline script

web/src/main/react-dashboard/src/components/DeploymentPatternView.js, web/src/main/react-dashboard/src/index.css
**Purpose**
Contains changes related to improving the way infrastructure parameters are displayed in the dashboard.
Resolves #695 
**Goals**
Improve dashboard UI
=> Improve Deployment Pattern View in dashboard

core/src/test/java/org/wso2/testgrid/core/command/GenerateTestPlanCommandTest.java, core/src/test/java/org/wso2/testgrid/core/command/RunTestPlanCommandTest.java, pom.xml
=> Update JMeter version

pom.xml
**Purpose**
Revert JMeter version to fix runtime issue in jenkins.
=> Rever jmeter version

automation/pom.xml, core/pom.xml
**Purpose**
Include selenium dependencies to TestGrid.
=> Add selenium dependencies

automation/pom.xml, pom.xml
**Purpose**
Revert Jmeter version bump.
=> Revert JMeter version and add Selenium as dependencies

pom.xml
**Purpose**
Change Selenium java version to fix test run issue
=> Change Selenium java version

docs/QuickStartGuide.md
**Purpose**
testgrid.yaml section in QuickStartGuide having incorrect indentations and due to that yaml not parsing properly. This PR is to update testgrid.yaml section with correct indentations.
**Goals**
Update testgrid.yaml with correct indentations.
**Approach**
Update testgrid.yaml with correct indentations.
=> Update testgrid.yaml with correct indentations.

common/src/main/java/org/wso2/testgrid/common/TestPlan.java, common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java, core/src/test/java/org/wso2/testgrid/core/command/GenerateTestPlanCommandTest.java, core/src/test/java/org/wso2/testgrid/core/command/RunTestPlanCommandTest.java, core/src/test/resources/test-plan-01.yaml
=> Revert "Support persisting Jenkins build number"

deployment/src/main/java/org/wso2/testgrid/deployment/DeploymentUtil.java, test-scripts/local-is-deployment/Solutions/solution01/jmeter/01-TestIS540.jmx, test-scripts/local-is-deployment/testgrid.yaml, test-scripts/tomcat-deployment/testgrid.yaml
**Purpose**
The local-is-deployment and tomcat-deployment test scripts has certain issues to conform with the latest testgrid.yaml syntax. This PR fixes them.
=> Conform sample testgrid.yaml files to new scenarioConfig.

deployment/src/main/java/org/wso2/testgrid/deployment/DeploymentUtil.java
**Purpose**
Fixes findbugs build failure
=> Fixes findbugs build failure

logging/pom.xml, pom.xml
=> Fix slf4j loading issue

web/src/main/react-dashboard/package-lock.json, web/src/main/react-dashboard/package.json
**Purpose**
This PR fixes Hek vulnerability issue. This resolves #739.
**Goals**
In order to fix the Hoek vulnerability issue update packages and update Hoek version from 4.2.0 to 4.2.1.  
**Approach**
N/A
=> Fix Hoek vulnerability issue

web/src/main/react-dashboard/src/components/DeploymentPatternView.js, web/src/main/react-dashboard/src/components/InfraCombinationView.js, web/src/main/react-dashboard/src/components/Login.js, web/src/main/react-dashboard/src/components/ProductStatusView.js, web/src/main/react-dashboard/src/components/ScenarioView.js, web/src/main/react-dashboard/src/components/SingleRecord.js, web/src/main/react-dashboard/src/components/TestRunView.js
**Purpose**
The purpose of this PR is to fix Travis-ci build failure.
**Goals**
There were some  ESLint rule breaks. Because of that Travice-ci build is failed. Hence, in order to compatible with   ESLint rules modified TestGrid dashboard source.
**Approach**
N/A
N/A
N/A
N/A
**Training**
N/A
N/A
**Marketing**
N/A
- Unit tests 
N/A
N/A
**Samples**
N/A
N/A
**Migrations (if …
=> Fix Travis-ci build failure 

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java
=> Update QA-Tomcat details

automation/src/main/java/org/wso2/testgrid/automation/parser/JMeterParserUtil.java, jenkins/pipelines/test-jobs/wso2apim-2.1.0-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2apim-2.2.0-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2ei-6.1.1-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2is-5.3.0-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2is-5.5.0-LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2is5.4.0LTS/Jenkinsfile, jenkins/pipelines/test-jobs/wso2is5.4.1LTS/Jenkinsfile
=> Update jenkin build jobs to cleanup test directories

automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterExecutor.java, automation/src/main/java/org/wso2/testgrid/automation/reader/JMeterTestReader.java, core/src/test/java/org/wso2/testgrid/core/command/RunTestPlanCommandTest.java
=> Rename scenario.sh script to run-scenario.sh

core/src/main/resources/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
Provides infrastructure provisioning scripts for APIM integration test jobs
Fixes #811
**Goals**
Integration tests need to be run in its own infrastructure that is separated from the testgrid deployment.
**Approach**
This provides a cloudformation script to provision an EC2 instance and a RDS based DB instance.
The intg tests need to be run inside this.
The userdata section of this EC2 instance contains a script that clones and build the `product-apim` repo. This MAY be removed from here later on. This is part of scenario test scripts.
=> Provides AWS infrastructure provisioning scripts for APIM integration test jobs

jenkins/pipelines/continuous-delivery/Jenkinsfile, jobs/wso2am-intg/Jenkinsfile, jobs/wso2am-intg/testgrid.yaml
**Purpose**
Add deploymentConfig section to wso2am-intg testgrid.yaml
=> Add deploymentConfig section to wso2am-intg testgrid.yaml

jobs/wso2am-intg/Jenkinsfile, test-scripts/local-is-deployment/job-config.yaml
**Purpose**
Added properties include:
```
echo 'properties:' >> ${JOB_CONFIG_YAML_PATH}
echo '  PRODUCT_GIT_URL: ${PRODUCT_GIT_URL}' >> ${JOB_CONFIG_YAML_PATH}
echo '  PRODUCT_GIT_BRANCH: ${PRODUCT_GIT_BRANCH}' >> ${JOB_CONFIG_YAML_PATH}
echo '  PRODUCT_DIST_DOWNLOAD_API: ${PRODUCT_DIST_DOWNLOAD_API}' >> ${JOB_CONFIG_YAML_PATH}
echo '  SQL_DRIVERS_LOCATION_UNIX: ${SQL_DRIVERS_LOCATION_UNIX}' >> ${JOB_CONFIG_YAML_PATH}
echo '  SSH_KEY_LOCATION: workspace/testgrid-key.pem' >> ${JOB_CONFIG_YAML_PATH}
echo '  REMOTE_WORKSPACE_DIR_UNIX: ${REMOTE_WORKSPACE_DIR_UNIX}' >> ${JOB_CONFIG_YAML_PATH}
echo '  REMOTE_WORKSPACE_DIR_WINDOWS: ${REMOTE_WORKSPACE_DIR_WINDOWS}' >> ${JOB_CONFIG_YAML_PATH}
echo '  gitURL: ${PRODUCT_GIT_URL}' >> ${JOB_CONFIG_YAML_PATH}
echo '  gitBranch: ${PRODUCT_GIT_BRANCH}' …
```
=> Adds custom properties to job-config.yaml

automation/src/main/java/org/wso2/testgrid/automation/report/FunctionalReportGenerator.java, core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java, core/src/main/java/org/wso2/testgrid/tinkerer/UnixClient.java, deployment/src/main/java/org/wso2/testgrid/deployment/deployers/AWSDeployer.java, jobs/wso2am-intg/testgrid.yaml
**Purpose**
Resolves #835 
Resolves #836 
+minor fixes
**Goals**
Ensure end to end execution of Integration tests builds on TestGrid.
**Approach**
Refactored the code and moved the agent registering section to the post-deployment phase
Added the test type to the integration test testgrid.yaml
=> Integration test execution related improvements

core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java, core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java, jobs/intg-test-resources/wso2-intg-test-cfn.yaml, jobs/wso2am-intg/Jenkinsfile
**Purpose**
The process status of the run-testplan should be a non-zero if the testplan failed.
**Goals**
Show failure status in jenkins dashboard.
=> The process status of the run-testplan should be a non-zero if the testplan failed.

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java, jobs/intg-test-resources/wso2-intg-test-cfn.yaml, jobs/wso2am-intg/Jenkinsfile, jobs/wso2am-intg/testgrid.yaml
**Purpose**
add cfn input properties into the output. We sometimes use default values (ex. DBUsername) of cfn input params which needs to passed down to the next step.
=>  Adds cfn input properties into the data-bucket

core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java, jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
Fix the os type identification issues and update the integration cloud formation script with the latest user data script
**Goals**
Execution of integration tests on TestGrid
=> Integration Cloud formation script related changes

automation/src/main/java/org/wso2/testgrid/automation/exception/ReportGeneratorNotFoundException.java, automation/src/main/java/org/wso2/testgrid/automation/executor/TestNgExecutor.java, automation/src/main/java/org/wso2/testgrid/automation/parser/TestNgResultsParser.java, automation/src/main/java/org/wso2/testgrid/automation/report/ReportGeneratorFactory.java, common/src/main/java/org/wso2/testgrid/common/TestCase.java, common/src/main/java/org/wso2/testgrid/common/TestPlan.java, common/src/main/java/org/wso2/testgrid/common/TestScenario.java, core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java, core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java, core/src/main/java/org/wso2/testgrid/tinkerer/TinkererClientFactory.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/aws/StackCreationWaiter.java
**Purpose**
Introduces a more specialized ReportGeneratorNotFoundException class.
Specialized class than the ReportGeneratorInitializationException for better error logging.
Print the infra combination at the beginning of run testplan.
=> Introduces a more specialized ReportGeneratorNotFoundException class

jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
Add conditional check for OS in Intg-cloudformation script
(As a part of getting integration test working on Windows)
=> Add conditional check for OS in Intg-cloudformation script

jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
The notation `AWS::NoValue` has to be within inverted commas.
**Samples**
**Learning**
=> Adding proper AWS::NoValue annotation

jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
Fixes the $subject.
=>  Fixed issue with YAML not well-formed due to AWS::NoValue

jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
Set cfn intg db DeletionPolicy from snapshot to delete.
**Goals**
This reduces the need to periodically clean the AWS db snapshots.
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> Set cfn intg db DeletionPolicy from snapshot to delete

jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
Resolves #861 
**Goals**
Integration build job execution on TestGrid
**Approach**
Updated the current instance name in the cloud formation signal
=> Update CloudFormation signal instance name

core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java, distribution/bin/testgrid, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/aws/StackCreationWaiter.java
**Purpose**
Print the cfn stack events in top-down order without duplicates
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> Print the cfn stack events in top-down order without duplicates

jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
Changing instance type of Windows instance into `m3.2xlarge` 
=> Change the instance type of Windows instance.

automation/src/main/java/org/wso2/testgrid/automation/parser/TestNgResultsParser.java, common/src/main/java/org/wso2/testgrid/common/config/PropertyFileReader.java, common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java, core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java, deployment-tinkerer/src/main/java/org/wso2/testgrid/deployment/tinkerer/providers/AWSProvider.java, deployment/src/main/java/org/wso2/testgrid/deployment/deployers/ShellDeployer.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/ShellScriptProvider.java, jobs/wso2am-intg/Jenkinsfile, reporting/src/main/java/org/wso2/testgrid/reporting/EmailReportProcessor.java, web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java
**Purpose**
Improve email and testng processing logs
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> Improve email and testng processing logs

automation/src/main/java/org/wso2/testgrid/automation/parser/TestNgResultsParser.java, automation/src/test/java/org/wso2/testgrid/automation/executor/TestNgResultsParserTest.java, automation/src/test/resources/artifacts/automation.log.rename, automation/src/test/resources/artifacts/surefire-reports/testng-results.xml, automation/src/test/resources/testng.xml
**Purpose**
Treat individual TestNG test methods as Testgrid test cases
**Goals**
**Approach**
Parse each `test-method` under `class` in testng-results.xml. 
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> Treat individual TestNG test methods as Testgrid test cases

core/src/main/java/org/wso2/testgrid/core/command/GenerateEmailCommand.java, jobs/wso2am-intg/Jenkinsfile, reporting/src/main/java/org/wso2/testgrid/reporting/EmailReportProcessor.java, reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngine.java
**Purpose**
Fix build failures occuring because of formatting issues
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets?yes
=> Fix build failures

core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateEmailCommand.java, reporting/src/main/java/org/wso2/testgrid/reporting/EmailReportProcessor.java, reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngine.java
**Purpose**
Log the derived directory path in email generation phase
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets?yes
=> Improve logs in email generation module

jenkins/pipelines/parallel-execution/Jenkinsfile
This PR handles creation of empty executors when parallel executor count is larger than test-plan count.
=> Handle creation of empty executors when parallel executor count is larger than test-plan count

common/src/main/java/org/wso2/testgrid/common/config/PropertyFileReader.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateEmailCommand.java, core/src/test/java/org/wso2/testgrid/core/TestPlanExecutorTest.java, reporting/pom.xml, reporting/src/main/java/org/wso2/testgrid/reporting/EmailReportProcessor.java, reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngine.java, reporting/src/test/java/org/wso2/testgrid/reporting/TestReportEngineTest.java, reporting/src/test/resources/job-config.yaml, reporting/src/test/resources/surefire-reports/TestSuite.txt, reporting/src/test/resources/test-plan-01.yaml, reporting/src/test/resources/testng.xml
**Purpose**
Add unit tests for email test report engine
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> Add unit tests for email test report engine

jenkins/pipelines/parallel-execution/Jenkinsfile
**Purpose**
Update parallel execution pipeline script to latest.
=> Update parallel execution pipeline script

web/src/main/react-dashboard/src/components/TestRunView.js
**Purpose**
Remove null value viewing in dashboard if config change set did not run.
=> Config change set

automation/src/main/java/org/wso2/testgrid/automation/parser/TestNgResultsParser.java, automation/src/test/java/org/wso2/testgrid/automation/executor/TestNgResultsParserTest.java, automation/src/test/resources/artifacts/surefire-reports/TEST-TestSuite.xml
**Purpose**
Resolves #895 
**Goals**
Use the surefire reports to process testcase details.
**Approach**
process xml file by each element to identify the passed, skipped and failed test cases
=> Use surefire reports to read testcase data

jobs/ballerina-message-broker-perf/Jenkinsfile, jobs/ballerina-message-broker-perf/testgrid.yaml
**Purpose**
Add ballerina-message-broker perf test job files provided by Hasitha
=> Add ballerina-message-broker perf test job files

common/src/main/java/org/wso2/testgrid/common/TestGridConstants.java, common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java, core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java, jobs/wso2am-intg/Jenkinsfile, web/src/main/java/org/wso2/testgrid/web/api/LogEventSocketMediator.java, web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java, web/src/main/react-dashboard/src/components/TestRunView.js
**Purpose**
The current TestRun view in dashboard opens the complete Test-Run.log which can cause the page to be freeze when the log file is large. With this option, the dashboard will only display a truncated version of the log-file while providing option to download the full-log.
fixes #903 
Sample truncated log:
```
[2018-07-19 11:53:50,960]  INFO {org.wso2.testgrid.core.command.RunTestPlanCommand} - Executing test-plan for infrastructure combination: 
{
DBEngine = mysql
DBEngineVersion = 5.7
JDK = OPEN_JDK8
OS = CentOS
OSVersion = 7.4
}
[2018-07-19 11:53:59,619]  INFO {org.wso2.testgrid.infrastructure.providers.AWSProvider} - Creating CloudFormation Stack 'single-node-ec2-and-rds-deployment-JAT79Z' in region 'us-east-1'. Script : jobs/intg-test-resources/wso2-intg-test-cfn.yaml …
```
=> Adds test-run log file truncation and view option.

common/pom.xml, common/src/main/java/org/wso2/testgrid/common/TestCase.java, common/src/main/java/org/wso2/testgrid/common/TestPlan.java, common/src/main/java/org/wso2/testgrid/common/infrastructure/InfrastructureCombination.java, common/src/main/java/org/wso2/testgrid/common/infrastructure/InfrastructureParameter.java, reporting/src/main/java/org/wso2/testgrid/reporting/EmailReportProcessor.java, reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngine.java, reporting/src/main/java/org/wso2/testgrid/reporting/summary/InfrastructureBuildStatus.java, reporting/src/main/java/org/wso2/testgrid/reporting/summary/InfrastructureSummaryReporter.java, reporting/src/main/resources/templates/email_report.mustache, reporting/src/test/java/org/wso2/testgrid/reporting/BaseClass.java, reporting/src/test/java/org/wso2/testgrid/reporting/TestReportEngineTest.java, reporting/src/test/java/org/wso2/testgrid/reporting/summary/InfrastructureSummaryReporterTest.java
**Purpose**
Generate email summary table for test-case to infrastructure mapping.
**Goals**
Deduce the exact infrastructure a given test-case fails on.
Algo:
=>  Generate email summary table for test-case to infrastructure mapping

jobs/wso2am-intg/Jenkinsfile
**Purpose**
Resolves #916 
**Goals**
Get notifications when a single test plan fails. or succeeds
**Approach**
Integrated the slack Jenkins plugin.
=> Add slack notifications to pipeline stages

dao/src/main/java/org/wso2/testgrid/dao/repository/TestPlanRepository.java, reporting/src/main/java/org/wso2/testgrid/reporting/ChartGenerator.java, reporting/src/main/java/org/wso2/testgrid/reporting/GraphDataProvider.java
**Purpose**
The purpose of this PR is to improve graph generating functionality.
**Goals**
In order to improve graph labels and data representation, modified the functionality.
- JDK - ORACLE JDK8
- OS - UBUNTU 18.04
- DB - MySQL5.7
=> Improve graph generating functionality

jenkins/pipelines/parallel-execution/Jenkinsfile
**Purpose**
This merges the jenkinsfile pipeline changes into git.
This contains the slack support implemented by sameera.
This also fixes S3 upload issue due to errors in the previous pipeline step.
**Groovy code indentation has been changed to 2 spaces.**
**Goals**
The pipeline should be maintained in source control at all times.
=> Jenkinsfile: S3 upload issue due to errors in the previous pipeline step

reporting/src/main/java/org/wso2/testgrid/reporting/ChartGenerator.java, reporting/src/main/resources/styles/summary.css
**Purpose**
Add custom styling sheet support for charts and improve charts
=> Add custom styling sheet support for charts and improve charts

common/src/main/java/org/wso2/testgrid/common/util/FileUtil.java, common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java, jenkins/pipelines/parallel-execution/Jenkinsfile, reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngine.java, reporting/src/main/resources/templates/summarized_email_report.mustache
**Purpose**
1. Email report: include dashboard url
2. Jenkinsfile: send a mail if summarized report could not be found.
=> Email report: include dashboard url

jenkins/pipelines/parallel-execution/Jenkinsfile
**Purpose**
Moved product-specific properties out of pipeline to preserve abstraction.
=> Update the jenkins pipeline for parallel execution.

reporting/src/main/java/org/wso2/testgrid/reporting/ChartGenerator.java, reporting/src/main/resources/templates/summarized_email_report.mustache
**Purpose**
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> Fix missing styling issue when forwarding generated email

common/src/main/java/org/wso2/testgrid/common/TestGridConstants.java, common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java, jenkins/pipelines/parallel-execution/Jenkinsfile, reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngine.java, reporting/src/main/resources/templates/summarized_email_report.mustache
**Purpose**
Generate chart URLs based on S3 bucket locations to resolve missing image issue when forwarding Emails.
Resolves #949
=> Generate chart URLs based on S3 bucket locations

deployment/src/main/java/org/wso2/testgrid/deployment/deployers/ShellDeployer.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/ShellScriptProvider.java
**Purpose**
Resolves #960 
**Goals**
Update the Shell Provisioner classes to use databucket concept
**Approach**
Replace the workspace logic with databucket logic
=> Add databucket changes to shell provisioner

jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
Write user-data log to a log file.
Resolves #986 
**Goals**
Troubleshooting
=> Write user-data log to a log file

automation/src/main/java/org/wso2/testgrid/automation/parser/TestNgResultsParser.java, automation/src/test/java/org/wso2/testgrid/automation/executor/TestNgResultsParserTest.java, automation/src/test/resources/testng.xml
**Purpose**
Resolves #994 
**Goals**
Fix the data provider suffix appending logic
**Approach**
Keep the original test name in a separate variable.
=> Update the data provider suffix logic

reporting/src/main/java/org/wso2/testgrid/reporting/ChartGenerator.java, reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngine.java
**Purpose**
This fixes wrong image displaying issue in summary Emails.
=> Add a unique ID to the name of generated graphs

reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngine.java
=> Fix string concat issue

reporting/src/main/java/org/wso2/testgrid/reporting/ChartGenerator.java, reporting/src/main/java/org/wso2/testgrid/reporting/EmailReportProcessor.java, reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngine.java, reporting/src/main/resources/templates/summarized_email_report.mustache
**Purpose**
Sending email when there are no test failures.
=> Send email when there are no test failures and email improvements

reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngine.java, reporting/src/main/resources/templates/summarized_email_report.mustache
**Purpose**
Fix test result table render issue when tests failed
=> Fix test result table render issue when tests failed

reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngine.java
**Purpose**
Contains changes related to getting the proper git revision in email reports.
Resolves #1002
=> Fix "Unknown" git revision in email report

reporting/src/main/java/org/wso2/testgrid/reporting/ChartGenerator.java, reporting/src/main/resources/templates/summarized_email_report.mustache
**Purpose**
Improve graphs in mail report. Resolves #941
=> Improve graphs in mail report

reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngine.java, reporting/src/main/resources/templates/summarized_email_report.mustache
**Purpose**
Contains changes related to fixing minor errors in the summarized email report.
=> Fix mustache template issues for infra errors

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java
**Purpose**
Increase stack creation timeout
=> Increase stack creation timeout

jobs/intg-test-resources/scripts/configure_product.py, jobs/intg-test-resources/scripts/const.py, jobs/intg-test-resources/scripts/cron-job.sh, jobs/intg-test-resources/scripts/deploy.py, jobs/intg-test-resources/scripts/deploy.sh, jobs/intg-test-resources/scripts/requirements.txt, jobs/intg-test-resources/scripts/rsync-for-carbon-depsync-unix.sh, jobs/intg-test-resources/static-configs/product-apim/publisher_site.json, jobs/intg-test-resources/static-configs/product-apim/store_site.json, jobs/intg-test-resources/static-configs/registry.xml, jobs/intg-test-resources/static-configs/user-mgt.xml, jobs/intg-test-resources/wso2-intg-test-2-node-cfn.yaml
=> Two-node deployment scripts for APIM

common/src/main/java/org/wso2/testgrid/common/plugins/AWSArtifactReader.java
**Purpose**
Fix results download failure on the dashboard TestRun view.
Resolves #1029 
=> Fix archive download failure in the dashboard

jobs/intg-test-resources/ballerina-intg-test-cfn.yaml
**Purpose**
Contains modifications to the Ballerina cloudformation script to install nodejs and npm in CentOS.
**Goals**
Run ballerina integration tests on TestGrid
=> Modify ballerina cloudforamtion script to install nodejs and npm

distribution/bin/log4j2.xml, logging/pom.xml, logging/src/main/java/org/wso2/testgrid/logging/plugins/LogFilePathLookup.java, web/src/main/java/org/wso2/testgrid/web/api/LogEventSocketMediator.java
**Purpose**
Contains the fix to create the test-run.log file location in the expected path (workspace). 
Resolves #1034 
=> Fix failure in downloading Test-Run log in TestGrid Dashboard

jobs/intg-test-resources/wso2-intg-test-2-node-cfn.yaml
**Purpose**
Add an entry to /etc/hosts in the apim nodes to resolve LB hostname to localhost.
=> Modify 2-node cloudformation script to add an entry to hosts file in CentOS

jenkins/slave-setup/ec2-slave-setup.sh
**Purpose**
Add ec2-slave-setup script which will be used by the slave setup plugin. 
=>  Add ec2-slave-setup script

jenkins/slave-setup/ec2-slave-setup.sh
**Purpose**
Fix distribution downloading path
=> Fix distribution downloading path

packer/resource-ami/config.sh, packer/resource-ami/packer-conf.json
**Purpose**
A wrong name was used with a command in the shell script.
**Learning**
=> Fix wrong file-name

jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
Add Red Hat Linux 7.4 to testgrid
**Goals**
Run tests in RHEL
**Approach**
Created an AMI for RHEL and added a new OS infra parameter to testgriddb. Finally modified the CF script
=> Add RHEL to CF script

jenkins/slave-setup/ec2-slave-setup.sh
**Purpose**
Set the JMETER_HOME env variable
**Goals**
Run JMETER tests from slave
**Approach**
set JMETER_HOME in bashrc
=> Set JMETER_HOME env variable

deployment/src/main/java/org/wso2/testgrid/deployment/deployers/ShellDeployer.java
**Purpose**
Contains changes to modify working directory of deploy.sh
=> modify working directory for deploy.sh

automation/src/main/java/org/wso2/testgrid/automation/parser/FunctionalTestResultParser.java, automation/src/main/java/org/wso2/testgrid/automation/parser/TestNgResultsParser.java, common/src/main/java/org/wso2/testgrid/common/TestGridConstants.java, common/src/main/java/org/wso2/testgrid/common/util/S3StorageUtil.java
=> Revert "Refactor scenario results zip path"

automation/src/main/java/org/wso2/testgrid/automation/parser/FunctionalTestResultParser.java, automation/src/main/java/org/wso2/testgrid/automation/parser/TestNgResultsParser.java
Uses scenario name to create the scenario results zip
=> Refactor scenario results zip path

common/src/main/java/org/wso2/testgrid/common/config/ConfigurationContext.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java
**Purpose**
Contains modifications related to adding config properties required for AWS clustering
=> Add new config properties for AWS clustering

dao/src/main/java/org/wso2/testgrid/dao/repository/TestPlanRepository.java
**Purpose**
Contains fix for the query to display latest build details of each deployment pattern.
=> Fix query to display latest build records for each deployment

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java
**Purpose**
Contains improvement related to logging the cloudformation outputs
=> Log cloudformation outputs

web/src/main/react-dashboard/src/components/DeploymentPatternView.js, web/src/main/react-dashboard/src/components/ProductStatusView.js
**Purpose**
Disable executing operations from dashboard until the coordination with Jenkins is properly set.
=> Disable executing operations from dashboard.

common/src/main/java/org/wso2/testgrid/common/config/ConfigurationContext.java, web/src/main/java/org/wso2/testgrid/web/sso/SSOSessionCheckFilter.java
**Purpose**
Create Authentication to call backend api without session cookies in order to test testgrid
**Approach**
Check for a  Authorization header.
=>  Add new token for backend API request authentication

common/src/main/java/org/wso2/testgrid/common/TestPlan.java, common/src/main/java/org/wso2/testgrid/common/config/DeploymentConfig.java, common/src/main/java/org/wso2/testgrid/common/config/ScenarioConfig.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java, core/src/test/resources/test-plan-01.yaml, core/src/test/resources/workspace/data-bucket/testplan-props.properties, test-scripts/resources/testgrid.yaml
**Purpose**
Move repo URLs to testgrid.yaml
=>  Move repo URLs to testgrid.yaml

packer/resource-ami/config.sh, packer/resource-ami/init.sh, packer/resource-ami/packer-conf.json
**Purpose**
Support RHEL 7.4 AMI creation from packer 
**Goals**
create the testgrid RHEL 7.4 AMI from packer
**Approach**
Created a new case in packer scripts for RHEL
=> Add RHEL to packer

common/src/main/java/org/wso2/testgrid/common/DeploymentCreationResult.java, common/src/main/java/org/wso2/testgrid/common/InfrastructureProvisionResult.java, common/src/main/java/org/wso2/testgrid/common/TestGridConstants.java, core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java, core/src/main/java/org/wso2/testgrid/core/command/FinalizeRunTestplan.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java, reporting/src/main/java/org/wso2/testgrid/reporting/EmailReportProcessor.java, reporting/src/main/java/org/wso2/testgrid/reporting/GraphDataProvider.java, reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngine.java, reporting/src/test/java/org/wso2/testgrid/reporting/BaseClass.java
**Purpose**
Show git repo URLs of infra, deploy, test steps in the email
=> Show git repo URLs of infra, deploy, test steps in the email

core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java, reporting/src/main/java/org/wso2/testgrid/reporting/EmailReportProcessor.java
**Purpose**
Fixing build failure
=> Fixing build failure

pom.xml, test/integration-tests/pom.xml, test/integration-tests/src/test/java/org/wso2/testgrid/TestProperties.java, test/integration-tests/src/test/java/org/wso2/testgrid/common/EmailUtils.java, test/integration-tests/src/test/java/org/wso2/testgrid/common/HostValidator.java, test/integration-tests/src/test/java/org/wso2/testgrid/tests/TestPhases.java, test/integration-tests/src/test/resources/email.properties, test/integration-tests/src/test/resources/log4j2.xml, test/integration-tests/src/test/resources/phase1-testgrid.yaml, test/integration-tests/src/test/resources/phase2-testgrid.yaml, test/integration-tests/src/test/resources/test-phase1/deploy.sh, test/integration-tests/src/test/resources/test-phase1/destroy.sh, test/integration-tests/src/test/resources/test-phase1/infra.sh, test/integration-tests/src/test/resources/test-phase1/test.sh, test/integration-tests/src/test/resources/testng.xml
**Purpose**
Adding Phase2 tests
=> Adding Phase2 tests

common/src/main/java/org/wso2/testgrid/common/InfrastructureProvisionResult.java, common/src/main/java/org/wso2/testgrid/common/config/DeploymentConfig.java, common/src/main/java/org/wso2/testgrid/common/config/InfrastructureConfig.java, core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/ShellScriptProvider.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/aws/AWSResourceManager.java, infrastructure/src/test/java/org/wso2/testgrid/infrastructure/AWSProviderTest.java, infrastructure/src/test/java/org/wso2/testgrid/infrastructure/providers/aws/AWSResourceManagerTest.java, reporting/src/main/java/org/wso2/testgrid/reporting/EmailReportProcessor.java
**Purpose**
Pass outputs of one infrastructure script to its subsequent infrastructure scripts within a given provisioner.
=> Pass outputs of one infrastructure script to its subsequent infrastructure scripts within a given provisioner

test/integration-tests/src/test/java/org/wso2/testgrid/tests/TestPhases.java
**Purpose**
Fix incorrect tg api url
=> Fix incorrect tg api url

test/integration-tests/src/test/java/org/wso2/testgrid/tests/TestPhases.java
**Purpose**
Fix incorrect tg api url
Read testgrid API key from a property file
=> Fix integration test issues

test/integration-tests/src/test/resources/phase1-testgrid.yaml
**Purpose**
Update phase-1 yaml
=> Update phase-1 yaml

jobs/test-resources/deploy.sh
**Purpose**
Fix url extraction issue in deploy.sh script
=>  Fix url extraction issue in deploy.sh script

distribution/bin/infra_params.sql
**Purpose**
Adds the infra_parameter.sql file in to WSO2-TestGrid.zip to use for creating the infrastructure_parameter table.
=> Package infra_params.sql into TestGird distribution

test/integration-tests/src/test/resources/phase1-testgrid.yaml, test/integration-tests/src/test/resources/phase2-testgrid.yaml, test/integration-tests/src/test/resources/test-phase1/test.sh
**Purpose**
Update test.sh and yaml file according to testgrid updates
=> Update Test files

test/integration-tests/src/test/resources/test-phase1/test.sh
=> Fix test.sh

common/src/main/java/org/wso2/testgrid/common/util/FileUtil.java, common/src/main/java/org/wso2/testgrid/common/util/tinkerer/ScriptExecutorThread.java, core/src/main/java/org/wso2/testgrid/core/ScenarioExecutor.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java, core/src/main/java/org/wso2/testgrid/tinkerer/ScriptExecutorThread.java, deployment-tinkerer/src/main/java/org/wso2/testgrid/deployment/tinkerer/beans/OperationMessage.java
**Purpose**
Print proper error message when test.sh/run-scenario.sh is not found
=> Print proper error message when test.sh/run-scenario.sh is not found

test/integration-tests/src/test/java/org/wso2/testgrid/tests/TestPhases.java
**Purpose**
Fix testgrid blackbox test failures
=> Fix testgrid blackbox test failures

test/integration-tests/src/test/java/org/wso2/testgrid/tests/TestPhases.java
**Purpose**
Fix  Phase1 test failure
=> Fix test failure

jenkins/slave-setup/ec2-slave-setup.sh
**Purpose**
This script is the one used in Testgrid dev. 
Add slave-setup.sh script from Tharindu's repo
=> Add slave-setup.sh script from Tharindu's repo

test/integration-tests/src/test/resources/phase2-testgrid.yaml
**Purpose**
Optimize Running time of phase 2. This will improve execution time by ~15 minutes.
=> Optimize Running time of phase 2

web/src/main/react-dashboard/package.json, web/src/main/react-dashboard/src/App.js, web/src/main/react-dashboard/src/components/DeploymentPatternView.js, web/src/main/react-dashboard/src/components/InfraCombinationHistory.js, web/src/main/react-dashboard/src/components/InfraCombinationOverview.js, web/src/main/react-dashboard/src/components/TestRunView.js, web/src/main/react-dashboard/src/constants.js, web/src/main/react-dashboard/src/containers/InfraCombinationOverviewContainer.js, web/src/main/react-dashboard/src/containers/InfrastructureContainer.js, web/src/main/react-dashboard/src/containers/TestRunContainer.js, web/src/main/react-dashboard/src/reducers/testGrid.js
**Purpose**
Merge infra combination history page and test plan page
=> Merge infra combination history page and test plan page

web/src/main/java/org/wso2/testgrid/web/api/ProductService.java, web/src/main/java/org/wso2/testgrid/web/bean/ProductStatus.java, web/src/main/react-dashboard/src/components/DeploymentPatternView.js
**Purpose**
Sort the list of jobs in react dashboard in alphabetical order
=> Sort the list of jobs in react dashboard in alphabetical order

test/integration-tests/src/test/java/org/wso2/testgrid/TestProperties.java, test/integration-tests/src/test/java/org/wso2/testgrid/tests/TestPhases.java
**Purpose**
Add authorization headers to jenkins invocations
=> Add authorization headers to jenkins invocations

test/integration-tests/src/test/java/org/wso2/testgrid/tests/TestPhases.java
**Purpose**
Fix test failures due to authorization issues.
=> Fix test failures due to authorization issues

dao/src/main/resources/META-INF/persistence.xml, pom.xml
Revert back to old persistence mode
=> Revert persistence mode

web/src/main/java/org/wso2/testgrid/web/api/APIUtil.java, web/src/main/java/org/wso2/testgrid/web/bean/TestPlan.java
**Purpose**
Adding Build url property to the TestPlan in web module.
=> Add build_url property to test plan

common/src/main/java/org/wso2/testgrid/common/util/S3StorageUtil.java
**Purpose**
Update the test result download path to the latest test-outputs.zip file location
=> Update s3 result location path

common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java, reporting/src/test/java/org/wso2/testgrid/reporting/BaseClass.java
**Purpose**
Fix incorrect infrastructure shown in the email report
=> Fix incorrect infrastructure shown in the email report

common/src/main/java/org/wso2/testgrid/common/GrafanaDashboardHandler.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java, test-scripts/testgrid.sh, test-scripts/tinkerer_start.sh
**Purpose**
Get performance data in Scenario tests
=> Get performance data in Scenario tests

jobs/intg-test-resources/wso2-intg-test-cfn.yaml, packer/resource-ami/config.sh, packer/resource-ami/init.sh
**Purpose**
This PR includes the necessary changes (in AMI creation steps and CloudFormation script) required to add AdoptOpenJDK8 support for integration tests.
Fixes https://github.com/wso2/testgrid/issues/1130
**Goals**
Add AdoptOpenJDK8 support for integration tests.
=> Add AdoptOpenJDK 8 support for integration tests

dao/src/main/resources/META-INF/persistence.xml, dao/src/test/resources/META-INF/persistence.xml
**Purpose**
Testgrid deployment has become unresponsive due to JPA hanging threads.
Detailed are mentioned in #1149.
Fixes #1149
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> Disable shared cache of EclipseLink JPA

test/integration-tests/src/test/resources/test-phase1/test.sh
**Purpose**
Update phase-1 tests for the current TG flow
=> Update phase-1 tests for the current TG flow

test/integration-tests/src/test/resources/test-phase1/test.sh
**Purpose**
Added missing arg for command
=> Added missing arg for command

test/integration-tests/src/test/resources/phase2-testgrid.yaml
**Purpose**
Change phase-2 test-repository
=> Change phase-2 test-repository

reporting/src/main/java/org/wso2/testgrid/reporting/EscalationEmailGenerator.java
**Purpose**
Improve logs in escalation-email generator
=> Improve logs in escalation-email generator

core/src/main/java/org/wso2/testgrid/core/command/GenerateEmailCommand.java, reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngine.java, reporting/src/main/resources/templates/infra_error_summary.mustache
**Purpose**
Generate separate email containing the infrastructure errors, to be sent the infrastructure script maintainers
=>  Add infra error email generation

core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java, core/src/main/java/org/wso2/testgrid/infrastructure/InfrastructureCombinationsProvider.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java
**Purpose**
- Parallel execution of uploading for each node.
- Modification for AWS-CLI installation at stack creation phase.
- Improvements on error logs at generate test-plan phase. 
=> Add improvements to deployment-output receiving steps

common/src/main/java/org/wso2/testgrid/common/GrafanaDashboardHandler.java, common/src/main/java/org/wso2/testgrid/common/config/ConfigurationContext.java, common/src/main/java/org/wso2/testgrid/common/util/tinkerer/TinkererSDK.java, core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateEmailCommand.java, reporting/src/main/java/org/wso2/testgrid/reporting/EmailReportProcessor.java, reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngine.java, reporting/src/test/java/org/wso2/testgrid/reporting/TestReportEngineTest.java, web/src/main/java/org/wso2/testgrid/web/api/APIUtil.java, web/src/main/java/org/wso2/testgrid/web/bean/TestPlan.java, web/src/main/react-dashboard/src/components/DeploymentPatternView.js, web/src/main/react-dashboard/src/components/InfraCombinationHistory.js, web/src/main/react-dashboard/src/components/ProductStatusView.js, web/src/main/react-dashboard/src/components/TestRunView.js
**Purpose**
- Show build number in the dashboard under test plans
- Make the job status button in dashboard home page clickable
- Show build number in the dashboard test plan history
- Improve Test plan view
- Fix locally grafana dashboard failure affecting run-testplan
- Handle ERROR state of builds in dashboard
- Remove older email report generation logic
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
- Confirmed that this PR doesn't commit any keys, passwords, tokens, …
=> Show build number in the dashboard under test plans

web/src/main/react-dashboard/src/App.js, web/src/main/react-dashboard/src/components/OutputFilesPopover.js, web/src/main/react-dashboard/src/components/TestRunView.js, web/src/main/react-dashboard/src/constants.js
**Purpose**
- Consolidate set of download options for a test-run.
- Add items to drawer
- Modify accordion
=> Improvements to TestGrid dashboard

web/src/main/react-dashboard/src/components/TestRunView.js
**Purpose**
Disable result-related buttons for tests in running state
=> Disable result-related buttons for tests in running state

dao/src/main/java/org/wso2/testgrid/dao/repository/TestPlanRepository.java, dao/src/main/java/org/wso2/testgrid/dao/uow/TestPlanUOW.java, reporting/src/main/java/org/wso2/testgrid/reporting/EmailReportProcessor.java, reporting/src/test/java/org/wso2/testgrid/reporting/TestReportEngineTest.java, web/src/main/java/org/wso2/testgrid/web/api/ProductService.java, web/src/main/java/org/wso2/testgrid/web/bean/ProductStatus.java, web/src/main/react-dashboard/src/components/DeploymentPatternView.js, web/src/main/react-dashboard/src/components/ProductStatusView.js, web/src/main/react-dashboard/src/components/SingleRecord.js
**Purpose**
Update TG dashboard statuses.
Add animation to running builds with showing previous status.
Minor alignment fixes.
=> Update TG dashboard statuses

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java
**Purpose**
Fix checkstyle issue
**Samples**
**Learning**
=> Fix checkstyle issue

common/src/main/java/org/wso2/testgrid/common/infrastructure/InfrastructureValueSet.java, core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java, core/src/main/java/org/wso2/testgrid/infrastructure/InfrastructureCombinationsProvider.java
**Purpose**
Fix issue where users had to mention at least one infrastructure from each infra type.
Fixes #1172
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=>  Fix issue where users had to mention at least one infrastructure from each infra type

automation/src/main/java/org/wso2/testgrid/automation/parser/TestNgResultsParser.java, core/src/main/java/org/wso2/testgrid/core/phase/TestPhase.java
**Purpose**
Provide better logs for testng results parsing
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> Provide better logs for testng results parsing

automation/src/main/java/org/wso2/testgrid/automation/parser/TestNgResultsParser.java, automation/src/test/java/org/wso2/testgrid/automation/executor/TestNgResultsParserTest.java, automation/src/test/resources/artifacts/automation.log.rename, automation/src/test/resources/artifacts/surefire-reports/TEST-org.myClass.xml
**Purpose**
Support all surefire-report files via the regex TEST-.*.xml instead of just TEST-TestSuite.xml
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> Support all surefire-report files via the regex TEST-.*.xml instead of just TEST-TestSuite.xml

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java
**Purpose**
Update AMI lookup params as to refer infra-properties of the test-plan.
=> Update AMI lookup params

core/src/main/java/org/wso2/testgrid/core/command/FinalizeRunTestplan.java
**Purpose**
Update finalize test-plan to run without product argument.
**Learning**
=> Update finalize test-plan to run without product argument

test/integration-tests/pom.xml
**Purpose**
Update blackbox-testing pom
=> Update blackbox-testing pom

common/src/main/java/org/wso2/testgrid/common/GrafanaDashboardHandler.java, core/src/main/java/org/wso2/testgrid/core/phase/InfraPhase.java
**Purpose**
Improve testgrid builds to run even if the grafana server is down
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> Improve testgrid builds to run even if the grafana server is down

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java
**Purpose**
Log dashboard generation failures should not lead to build failures.
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> Log dashboard generation failures should not lead to build failures.

jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> Adding c3.4xlarge as allowed value

common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java, dao/src/main/java/org/wso2/testgrid/dao/dto/TestCaseFailureResultDTO.java
**Purpose**
Fix infra-param retrieving issue
=> Fix infra-param retrieving issue

core/src/main/java/org/wso2/testgrid/core/command/FinalizeRunTestplan.java
**Purpose**
Fix minor code issue.
=> Fix minor code issue

automation/src/main/java/org/wso2/testgrid/automation/parser/TestNgResultsParser.java
**Purpose**
Ignore junitreports dir when scanning for TEST-.*.xml files
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> Ignore junitreports dir when scanning for TEST-.*.xml files

jobs/intg-test-resources/wso2-intg-test-cfn.yaml, packer/resource-ami/config.sh
**Purpose**
Purpose of this PR is to add corretto JDK support to existing AMI's
**Goals**
**Approach**
https://github.com/wso2/product-ei/issues/3433
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> Add CorrettoJDK-8 in packer file

packer/resource-ami/config.sh
**Purpose**
Changing the cacerts file of corretto jdk with AdoptOpenJDK to solve the certificate missing issue in IS.
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> Fixing the certificate issue in correttojdk-centos

packer/resource-ami/config.sh, packer/resource-ami/init.sh
**Purpose**
This PR includes changes in creating Ubuntu AMI. As well as changes of adding Adopt and corretto JDK in Centos. 
**Goals**
**Approach**
https://github.com/wso2/product-ei/issues/3433
Bug fixes
https://github.com/wso2/testgrid/issues/1199
https://github.com/wso2/testgrid/issues/1201
**Training**
**Marketing**
- Unit tests 
**Samples**
**Migrations (if …
=> Add Ubuntu AMI changes

common/src/main/java/org/wso2/testgrid/common/ShellExecutor.java, core/src/main/java/org/wso2/testgrid/core/Main.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java, jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
Download AWS EC2 instance system logs on stack creation failure.
This helps to track down issues with userdata shell scripts.
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> Download AWS EC2 instance system logs on stack creation failure

automation/src/main/java/org/wso2/testgrid/automation/parser/JMeterTestResultParser.java, automation/src/test/java/org/wso2/testgrid/automation/executor/JMeterExecutorTest.java, automation/src/test/resources/artifacts/broken.jtl, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java, reporting/src/main/java/org/wso2/testgrid/reporting/EmailReportProcessor.java, web/src/main/react-dashboard/src/components/TestRunView.js
**Purpose**
Fixes NPEs due to invalid jtl files.
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> Improve JMeter jtl result parser to validate jtl file first

jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
This PR is for set JAVA_HOME bin path in windows system environment to .resolve the EI test integration issues occurred in Windows Infrastructure. Error is shown below.
`IO Exception: "java.io.IOException: Cannot run program ""javac"": CreateProcess error=2, The system cannot find the file specified"; SQL statement: CREATE ALIAS getId AS $$ ResultSet query(Connection conn, String nameVal) throws SQLException { String sql = "select * from company where name = '" + nameVal + "'";return conn.createStatement().executeQuery(sql); } $$; [90028-140]`
**Goals**
This fix is getting added when running the cloudformation script. While it's running it set the above JAVA_HOME path as a system environment variable in the windows instance. 
**Approach**
Set the "%JAVA_HOME\bin" path in …
=> Set JAVA path to Windows environment variable

jobs/intg-test-resources/wso2-intg-test-cfn.yaml
…able
**Purpose**
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> Revert the change of setting up JAVA path to Windows environment variable

common/src/main/java/org/wso2/testgrid/common/TestPlanPhase.java, reporting/src/main/java/org/wso2/testgrid/reporting/EmailReportProcessor.java, reporting/src/main/java/org/wso2/testgrid/reporting/TestReportEngine.java, reporting/src/main/resources/templates/summarized_email_report.mustache, reporting/src/test/java/org/wso2/testgrid/reporting/BaseClass.java
**Purpose**
Show test errors in the email report
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> Show test errors in the email report

test/integration-tests/src/test/resources/phase1-testgrid.yaml, test/integration-tests/src/test/resources/phase2-testgrid.yaml
**Purpose**
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> Fix emailtolist

automation/src/main/java/org/wso2/testgrid/automation/parser/TestNgResultsParser.java, automation/src/test/java/org/wso2/testgrid/automation/executor/TestNgResultsParserTest.java, common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java, core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java, core/src/main/java/org/wso2/testgrid/core/phase/InfraPhase.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java, reporting/src/main/resources/templates/summarized_email_report.mustache, test/integration-tests/pom.xml
**Purpose**
Improve logs for better troubleshooting
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> Improve logs for better troubleshooting

test/integration-tests/src/test/java/org/wso2/testgrid/tests/TestPhases.java, web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java, web/src/main/react-dashboard/src/App.js, web/src/main/react-dashboard/src/components/InfraCombinationHistory.js, web/src/main/react-dashboard/src/components/OutputFilesPopover.js, web/src/main/react-dashboard/src/components/TestRunView.js
**Purpose**
Add test plan delete button to dashboard
**Goals**
Delete incomplete builds due to failures at different stages like preparation or infra provisioning, where the reason is intermittent not directly correlated to the actual tests.
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> Add test plan delete button to dashboard

common/src/main/java/org/wso2/testgrid/common/ShellExecutor.java, common/src/main/java/org/wso2/testgrid/common/TestGridConstants.java
**Purpose**
change the script file location
=> add-scripts-location

resources/k8s/WUMUpdateOnK8SVerifier, resources/k8s/build_latest.sh, resources/k8s/docker_build.sh
>  Build WSO2 product images within Jenkins. 
> Docker images for WSO2 products are built with the latest updates from UAT. These images are pushed onto a Registry where it'll be pulled when running tests for the relevant product.
> Two new scripts for the image building tasks which are executed with a Jenkins pipeline "WUMUpdateOnK8SVerifier".
=> Merging Docker image build with updates from UAT

core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java
This PR resolves #1127 - validate input for config name property.
=> Resolve issue #1127

deployment/src/main/resources/kubernetes_helmDeploy.sh, infrastructure/src/main/resources/kubernetes_helmInfra.sh
Transfer from using helm v2.4 to helm v3.0
=> Kuberenetes deployment

deployment/src/main/resources/kubernetes_helmDeploy.sh
=> modify database helm installation

common/src/main/java/org/wso2/testgrid/common/GrafanaDashboardHandler.java, core/src/main/java/org/wso2/testgrid/core/command/RunTestPlanCommand.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java, infrastructure/src/main/resources/kubernetes_helmInfra.sh, infrastructure/src/main/resources/kubernetes_infra.sh, reporting/src/main/java/org/wso2/testgrid/reporting/ChartGenerator.java
**Purpose**
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> Increase ec2 instance log output sizes for better cfn failure debugging

infrastructure/src/main/resources/kubernetes_helmInfra.sh, resources/k8s/WUMUpdateOnK8SVerifier.groovy, resources/k8s/build_latest.sh, resources/k8s/docker_build.sh
**Purpose**
When running in parallel, the firstly created *gcloud*.tar exists thus pipeline exits with an error. 
**Goals**
Resolve the error mentioned in $purpose.
=>  Add check for gcloud.tar to avoid file exists error

deployment/src/main/resources/kubernetes_helmDeploy.sh
=> Revert "Change helm version"

deployment/src/main/resources/kubernetes_helmDeploy.sh
**Purpose**
Resolves #1244 
**Goals**
Upgrading the Helm Version.
According to https://github.com/helm/helm/issues/5628#issuecomment-513254697 they are working on the issue, and it is resolved with the latest alpha 2 release. 
**Approach**
Helm version is upgraded to the latest helm3-alpha2.
=> Upgrade helm version

common/src/main/java/org/wso2/testgrid/common/ShellExecutor.java, core/src/main/java/org/wso2/testgrid/core/phase/DeployPhase.java, core/src/main/java/org/wso2/testgrid/core/phase/InfraPhase.java, core/src/test/java/org/wso2/testgrid/core/command/BaseTest.java, core/src/test/java/org/wso2/testgrid/core/command/DeployFailTest.java, core/src/test/java/org/wso2/testgrid/core/command/TestBase.java, core/src/test/resources/multi-deploy-script-test/workspace/README.md, core/src/test/resources/multi-deploy-script-test/workspace/deployment/deploy-3.sh, core/src/test/resources/multi-deploy-script-test/workspace/deployment/deploy-fail.sh, core/src/test/resources/multi-deploy-script-test/workspace/deployment/deploy.sh, core/src/test/resources/multi-deploy-script-test/workspace/infrastructure/destroy.sh, core/src/test/resources/multi-deploy-script-test/workspace/infrastructure/infra.sh, core/src/test/resources/multi-deploy-script-test/workspace/job-config.yaml, core/src/test/resources/multi-deploy-script-test/workspace/scenarioTests/ref-scenario-jmeter/tests/is-deployment-sample-tests.jtl, core/src/test/resources/multi-deploy-script-test/workspace/scenarioTests/ref-scenario-jmeter/tests/scenario22.jtl, core/src/test/resources/multi-deploy-script-test/workspace/scenarioTests/ref-scenario-jmeter/tests/test.sh, core/src/test/resources/multi-deploy-script-test/workspace/scenarioTests/ref-scenario/tests/test.sh, core/src/test/resources/multi-deploy-script-test/workspace/testgrid.yaml, core/src/test/resources/testng.xml, deployment/src/main/java/org/wso2/testgrid/deployment/deployers/ShellDeployerFactory.java, pom.xml, remoting-agent/pom.xml, test-scripts/local-is-deployment/.testgrid.yaml, web/src/main/react-dashboard/package-lock.json
**Purpose**
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> Skip remaining deploy scripts if the current deploy script exec failed

infrastructure/src/main/resources/kubernetes_helmInfra.sh, resources/k8s/WUMUpdateOnK8SVerifier.groovy, resources/k8s/build_latest.sh, resources/k8s/docker_build.sh, resources/k8s/dockerfile-generate/alpine/Dockerfile, resources/k8s/dockerfile-generate/centos/Dockerfile, resources/k8s/dockerfile-generate/dockerfile-generator.sh, resources/k8s/dockerfile-generate/ubuntu/Dockerfile
**Purpose**
Change docker image build scripts to generate dockerfile and build instead of downloading the dockerfile.
=> Change docker image build scripts 

infrastructure/src/main/resources/kubernetes_helmInfra.sh
**Purpose**
Resolves #1244 
**Goals**
Change the context for each shell session by changing the KUBECONFIG environment variable.
=> Modify context with KUBECONFIG environment variable

infrastructure/src/main/resources/kubernetes_helmInfra.sh, resources/k8s/docker_build.sh
This reverts commit b6d1b4916b160689e675bfd6099700c7c8893b59.
**Purpose**
Content added here is duplicated in [1].
[1] https://github.com/wso2-support/kubernetes-apim/blob/master/testgrid-scripts/deploy.sh 
**Goals**
Removing duplicated code content.
=> Revert "Modify context with KUBECONFIG env"

deployment/src/main/resources/kubernetes_helmDeploy.sh
**Purpose**
Upgrade from helm3-alpha.2 to helm3-beta.3. 
**Goals**
Using a more stable version of Helm.
=> Upgrade helm version to beta.3

deployment/src/main/resources/kubernetes_helmDeploy.sh
**Purpose**
Add su permission to install helm. 
**Goals**
Use helm for kubernetes deployment.
=> Add su permission to mv

resources/k8s/docker_build.sh
**Purpose**
Clean GCR stack by removing untagged images. 
**Goals**
Clean GCR stack
=> Clean GCR Stack

jobs/intg-test-resources/wso2-intg-test-cfn.yaml
**Purpose**
Add OPEN_JDK11 to the Integration tests
**Goals**
Add OPEN_JDK11 to the Integration tests
Ubuntu 18.04
=> Add OPEN_JDK11

core/src/main/java/org/wso2/testgrid/core/phase/TestPhase.java
This PR resolves #1249 - NPE when test.sh location is not specified in tg yaml
=> Resolve issue #1249

packer/resource-ami/config.sh
**Purpose**
This PR is for adding Open JDK 11 path for CentOS and Ubuntu.
=> Add Open JDK 11 path

test/integration-tests/src/test/resources/phase1-testgrid.yaml, test/integration-tests/src/test/resources/phase2-testgrid.yaml
=> Change notification email to WSO2 email

core/src/main/java/org/wso2/testgrid/core/phase/TestPhase.java
=> Fix product logs & dump uploading issue

distribution/bin/infra_params.sql, reporting/src/main/java/org/wso2/testgrid/reporting/GraphDataProvider.java
**Purpose**
Fixes #1292 
Fixes #1291
=> Fix incorrect database entry and Email generation issue for jobs without all infra params

automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterExecutor.java, common/src/main/java/org/wso2/testgrid/common/ShellExecutor.java, deployment/src/main/java/org/wso2/testgrid/deployment/deployers/ShellDeployerFactory.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/ShellScriptProviderFactory.java
**Purpose**
Add test script name as a prefix for test script logs.
Fixes #1294
=> Add script name as a prefix in log

packer/resource-ami/config.sh
**Purpose**
Apply the configuration in [1].
1. https://is.docs.wso2.com/en/next/setup/performance-tuning-recommendations/
**Goals**
Tune Performance
#1300 
#1301 
#1302 
AWS
Ubuntu/CentOS
=> Tune Performance for Unix instance

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java
**Purpose**
existing ${customuserdata} is not compatible with the SUSE 12 operating system.
**Goals**
Update to support SUSE 12
=> Support SUSE 12

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java
**Purpose**
Update SUSE 12 check  condition
=> Update SUSE 12 check  condition

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java
**Purpose**
Update SUSE 12 check condition
=> Update SUSE 12 check condition

infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java
**Purpose**
Fix 'if' condition for OS selection
=> Fix if condition for OS selection

aws/network.yaml
**Purpose**
Add the network configurations needed for centralized Puppetmaster
**Goals**
Fixes #1317 
AWS
=> Add TestGrid network

jobs/intg-test-resources/wum-releases/ansible-deployment/deploy.sh, jobs/intg-test-resources/wum-releases/ansible-deployment/run-deploy-script.sh, jobs/intg-test-resources/wum-releases/run-test.sh, jobs/intg-test-resources/wum-releases/wso2-wum-intg-test-cfn.yaml
**Purpose**
Update integration test resources
=> Update integration test resources

jobs/intg-test-resources/wum-releases/wso2-wum-intg-test-cfn.yaml
This is to change RHEL AMI
**Purpose**
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> Modify RHEL AMI

aws/database.yaml
**Purpose**
Add common CloudFormation Script for DB Creation
**Goals**
Fixes #1319 
AWS
=> Add common CloudFormation Script for DB Creation

jobs/intg-test-resources/infra.json, jobs/intg-test-resources/wum-releases/wso2-wum-intg-test-cfn.yaml
**Purpose**
This PR adds OPEN_JDK8 and updates the AMI to RedHat 7.
=> Update configurations to support OpenJDK8, RedHat 7

jobs/intg-test-resources/wum-releases/wso2-wum-intg-test-cfn.yaml
**Purpose**
This adds t2.xlarge instance type to allowed values of WSO2InstanceType.
=> Add t2.xlarge instance as allowed value of WSO2InstanceType

jobs/intg-test-resources/infra.json, jobs/intg-test-resources/wum-releases/wso2-wum-intg-test-cfn.yaml
**Purpose**
This PR adds Oracle_JDK11 and Corretto_JDK11 under JDK list.
=> Add support for Oracle_JDK11 and Corretto_JDK11

jobs/intg-test-resources/master-branch-releases/wso2-master-intg-test-cfn.yaml
**Purpose**
Adding a new instance type
=> Adding a new instance type

jobs/intg-test-resources/master-branch-releases/wso2-master-intg-test-cfn.yaml
**Purpose**
Adding mssql tool support
=> Adding mssql tool support

jobs/intg-test-resources/master-branch-releases/wso2-master-intg-test-cfn.yaml
**Purpose**
Adding DB instance class for SQL Server 15
=> Adding DB instance class for SQL Server 15

jobs/intg-test-resources/master-branch-releases/wso2-master-intg-test-cfn.yaml
Adding a new DB instance type to support MS SQL 15
=> Adding a new DB instance type

common/src/main/java/org/wso2/testgrid/common/TestGridConstants.java, common/src/main/java/org/wso2/testgrid/common/config/ConfigurationContext.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java
**Purpose**
New Testgrid parameters are required in Testgrid job For Openbanking 3.0.0 Latest jenkins build.
JenkinsUsername and JenkinsAPIToken will be mentioned in the CF script since they are required to download the latest built OB solution packs from Jenkins.
https://wso2.org/jenkins/job/financial-open-banking_OB-3.0.0/
**Goals**
Enable a new parameter in testgrid core.
**Approach**
**Training**
**Marketing**
- Unit tests 
- Confirmed that this PR doesn't commit any keys, passwords, …
=> Add new TestGrid Parameter

common/src/main/java/org/wso2/testgrid/common/TestGridConstants.java, common/src/main/java/org/wso2/testgrid/common/config/ConfigurationContext.java, infrastructure/src/main/java/org/wso2/testgrid/infrastructure/providers/AWSProvider.java
**Purpose**
New Testgrid parameters for CF script - GithubUsername, GithubAccessToken are added.
They are required since the Open Banking puppet scripts will be cloned through CF script .
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> Add Github credential parameters

jobs/intg-test-resources/update2-releases/ansible-deployment/deploy.sh, jobs/intg-test-resources/update2-releases/ansible-deployment/run-deploy-script.sh, jobs/intg-test-resources/update2-releases/run-test.sh, jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml, jobs/intg-test-resources/update2-releases/wso2-update.sh
Add initial u2 integration build scripts
=> Add initial u2 integration build scripts

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> hardcode db type to m5.xlarge

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> remove quotes

aws/is-custom.yaml, jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> Add Instance type

jobs/intg-test-resources/update2-releases/run-test.sh
**Purpose**
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> add uat-settings.xml

jobs/intg-test-resources/update2-releases/run-test.sh, jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> bring uat-setting into s3

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
=> change aws cli command

jobs/intg-test-resources/update2-releases/run-test.sh, jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> change ami

jenkins/slave-setup/ec2-slave-setup.sh
**Purpose**
$subject
Mail: Scenario Test Results for WUM Updates! #(1044) - WSO2 TestGrid
=> Add EI backends to known hosts

common/src/main/java/org/wso2/testgrid/common/GrafanaDashboardHandler.java, core/src/main/java/org/wso2/testgrid/core/phase/InfraPhase.java
=> Remove Grafana Dashboard configs temporarily

common/src/main/java/org/wso2/testgrid/common/GrafanaDashboardHandler.java, core/src/main/java/org/wso2/testgrid/core/phase/InfraPhase.java
=> Revert "Remove Grafana Dashboard configs temporarily"

common/src/main/java/org/wso2/testgrid/common/GrafanaDashboardHandler.java, core/src/main/java/org/wso2/testgrid/core/phase/InfraPhase.java
=> Add more logs

core/src/main/java/org/wso2/testgrid/core/phase/InfraPhase.java
=> Fix unused import error

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
> To support Temurin JDKs in Test Grid.
=> Add support for Temurin Open JDK 8

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
> To support Temurin JDKs in Test Grid
=> Fix sym link creation, fix java setup

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
> To support Temurin JDKs in Test Grid
=> Resolve java and javac version conflict

jobs/intg-test-resources/master-branch-releases/wso2-master-intg-test-cfn.yaml
$subject
**Purpose**
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> Add jq installed AMI to run tests on RHEL

jobs/intg-test-resources/infra.json
**Purpose**
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> update database drivers

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
Add wso2am-4.1.0 into integration testgrid
=> update the ami-0487db43bff239327

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
=> fix awscli installation

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
=> Update Intg CFN file

jobs/intg-test-resources/update2-releases/wso2-update.sh
=> Revert "Download given APIM pack from github"

jobs/intg-test-resources/update2-releases/run-test.sh, jobs/intg-test-resources/update2-releases/wso2-update.sh
**Changes**
1. Download APIM pack from Jenkins build instead of building it.
1. https://github.com/wso2/testgrid/pull/1416
2. https://github.com/wso2/testgrid/pull/1417
=> Download product pack from jenkins build

jobs/intg-test-resources/update2-releases/wso2-update.sh
=> Add temporary product download link for testing

jobs/intg-test-resources/update2-releases/wso2-update.sh
=> Revert "Add temporary product download link for testing"

jobs/intg-test-resources/master-branch-releases/wso2-master-intg-test-cfn.yaml
**Purpose**
Fix CFN script by adding default values and changing param names
=> Add default values and change parameter names

jobs/intg-test-resources/master-branch-releases/wso2-master-intg-test-cfn.yaml
**Purpose**
Replace EC2KeyPair instances with KeyPairName
=> Add variable name changes

jobs/intg-test-resources/master-branch-releases/wso2-master-intg-test-cfn.yaml
**Purpose**
Add missing instance types
=> Add missing instance types

jobs/intg-test-resources/master-branch-releases/wso2-master-intg-test-cfn.yaml
**Purpose**
Add AWS key info to cfn script
=> Add AWS key info to cfn script

jobs/intg-test-resources/master-branch-releases/wso2-master-intg-test-cfn.yaml
**Purpose**
Add changes to the master cfn script
=> Add changes to the master cfn script

jobs/intg-test-resources/master-branch-releases/wso2-master-intg-test-cfn.yaml
**Purpose**
Add JDK17 to allowed values
=> Add JDK17 to allowed values

jobs/intg-test-resources/master-branch-releases/wso2-master-intg-test-cfn.yaml
=> Add debug logs

jobs/intg-test-resources/master-branch-releases/wso2-master-intg-test-cfn.yaml, jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
Remove Oracle JDK and fix DB parameters not getting allocated issue.
=> Remove Oracle JDK and fix DB issue 

jobs/intg-test-resources/master-branch-releases/wso2-master-intg-test-cfn.yaml
**Purpose**
Fix DB default values
=> Fix DB default values

jobs/intg-test-resources/master-branch-releases/wso2-master-intg-test-cfn.yaml
**Purpose**
Modify DBEngineMap with new parameters
=> Modify DBEngineMap with new parameters

jobs/intg-test-resources/master-branch-releases/wso2-master-intg-test-cfn.yaml
**Purpose**
Add DB licence info
=> Add DB licence info

jobs/intg-test-resources/master-branch-releases/wso2-master-intg-test-cfn.yaml
**Purpose**
Fix issues in script and add debug logs to check database
=> Fix issues in bash script

jobs/intg-test-resources/master-branch-releases/wso2-master-intg-test-cfn.yaml
**Purpose**
Reformat userdata section
=> Reformat userdata section

jobs/intg-test-resources/master-branch-releases/wso2-master-intg-test-cfn.yaml
**Purpose**
Fix product version not getting added issue
=> Fix product version not getting added issue

jobs/intg-test-resources/master-branch-releases/wso2-master-intg-test-cfn.yaml
=> Revert "Fix product version not getting added issue"

jobs/intg-test-resources/master-branch-releases/wso2-master-intg-test-cfn.yaml
**Purpose**
Fix parameter issue in cfn script
=> Fix parameter issue in cloudformation

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn-db-test-temp.yaml
=> Add Tempory CFN script to test DB not setting up issue

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn-db-test-temp.yaml
=> Fix syntax errors in tempory CFN

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
Upgrade PostgreSQL version to 15.3
=> Upgrade PostgreSQL version to 15.3

jobs/intg-test-resources/update2-releases/wso2-update.sh
**Purpose**
This PR adds the flag to preserve environment variables for the update tool.
=> Add flag to preserve environment for update tool

jobs/intg-test-resources/update2-releases/wso2-update.sh
**Purpose**
This PR adds the flag to preserve environment variables for the update tool in the self update path.
=> Add flag to preserve environment for update tool to self update path

jobs/intg-test-resources/master-branch-releases/wso2-master-intg-test-cfn.yaml
This pr will update the RHEL image version to 8.7
=> Update RHEL image to 8.7

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
This Pr will update Postgresql version to 15
=> Update postgresql version

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
Support RHEL 9.3
Support SQL Server 2022(16.00)
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> Upgrade Testgrid scripts

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> Fix formatting error

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
**Goals**
**Approach**
**Training**
**Marketing**
- Unit tests 
**Samples**
**Learning**
=> Add AMI with updated cfn scripts

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
=> Update AMI to support DBs

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
=> Upgrade RHEL AMIs

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
=> Support Rocky Linux 9.3

jobs/intg-test-resources/update2-releases/run-test.sh
=> Source .bashrc before executing DB scripts

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
Fix DB Engine for Oracle 21
=> Fix oracle 21 DB Engine

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
=> Add new EC2 instance type

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
=> Install Git in Rocky linux

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
=> Install psql in Rocky Linux

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
=> Add Product parameter to cfn to support other products

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
Instances types have been updated to reduce the cost 
Old
c3.xlarge - $0.21
c4.2xlarge - $0.398
New
c7g.xlarge - $0.1445 (Graviton - ARM64)
c7g.2xlarge - $0.289 (Graviton - ARM64)
c6a.2xlarge - $0.306
c6a.xlarge - $0.153
=> Update Instance types

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
(cherry picked from commit d5402b96128a9fa37a570e186d0c1cf495bdd605)
$subject
=> Fix signature verification error when installing psql

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
This PR adds the AMI for Ubuntu 24.04.
=> Add AMI for Ubuntu 24.04

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
Fix some syntax issues in the cfn file.
=> Fix syntax issues related to the 

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
This PR replaces the environment variable from the CFN script to fix the build issue.
=> Replace environment variable from the CFN script

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
This PR fixes some syntax issues in the added block for Ubuntu 24.04.
=> Fix syntax issues in the added block for Ubuntu 24.04

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
This PR adds the script to get keys from the S3 for Ubuntu AMIs.
=> Add script to get keys from the S3 for Ubuntu

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
This PR adds the step to accept EULA for MSSQL clients for ubuntu instances.
=> Add step to accept EULA for MSSQL clients

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
This PR adds MSSQL executable path to bashrc and bash_profile for Ubuntu
=> Add MSSQL executable to bashrc and bash_profile for Ubuntu

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
Add MSSQL path to sudoers PATH variable.
=> Add MSSQL path to sudoers PATH variable

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
Adding this as per https://docs.aws.amazon.com//AmazonRDS/latest/PostgreSQLReleaseNotes/postgresql-release-calendar.html#PostgreSQL.Concepts.VersionMgmt.Supported
=> Add latest supported Postgres version

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
$subject
This pull request updates the `jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml` file to add support for Postgres 17.4.
Database version updates:
* Added `Postgres-17.4` to the list of supported database versions in the `Parameters` section.
* Added a mapping for `Postgres-17.4` in the `Mappings` section to specify its `DBEngine`.
=> Add PostgreSQL 17.4

jobs/intg-test-resources/master-branch-releases/wso2-master-is-intg-test-cfn.yaml
**Purpose**
$subject
**Related Issues**
- https://github.com/wso2-enterprise/iam-engineering/issues/1121
=> Onboard integration pipelines for Identity Server master pipelines

jobs/intg-test-resources/master-branch-releases/wso2-master-is-intg-test-cfn.yaml
**Purpose**
$subject
**Related Issues**
- https://github.com/wso2-enterprise/iam-engineering/issues/1121
=> Refactor script retrieval process and remove additional rhel ami in IS master pipeline

jobs/intg-test-resources/master-branch-releases/wso2-master-is-intg-test-cfn.yaml
=> Fix master versions and logging in IS master pipeline

jobs/intg-test-resources/update2-releases/wso2-u2-is-intg-test-cfn.yaml
**Purpose**
$subject
- https://github.com/wso2/testgrid/pull/1507
- https://github.com/wso2/testgrid/pull/1508
- https://github.com/wso2/testgrid/pull/1509
=> Onboard integration pipelines for Identity Server u2 pipelines

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
Update PostgresSQL version 12.15 to 12.22
=> Update PostgresSQL version 12.15 to 12.22

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml, jobs/intg-test-resources/update2-releases/wso2-update.sh
**Purpose**
The current TestGrid build does not support running tests at the staging level. This PR adds support for executing tests in the staging state.
**Goals**
Enable running integration tests on a staging pack.
**Approach**
Update the scripts to export WSO2_UPDATES_UPDATE_LEVEL_STATE=TESTING before running the update tool.
=> Staging support to testgrid

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
=> Revert "Update Rocky AMI"

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
This PR adds back the changes added via https://github.com/wso2/testgrid/pull/1519
- Reverts wso2/testgrid#1520
=> Update Rocky AMI

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
DB2 Onboarding
Execute integration tests on the DB2 database.
- Add DB2 related configuration to cloudformation file
- Fix indentation issue
Ran integration test group 1 for APIM 4.4.0.  
[View Test Results](https://testgrid.wso2.com/job/U2/job/Integration-Tests/job/product-apim/job/utils/job/apim-4.4.0-intg-testgrid-pipeline-db2/14/console)
https://github.com/wso2/testgrid-jenkins-library/pull/276
=> Db2 onboard

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
Update rocky image: install git
=> Update rocky image: install git

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**  
TestGrid build failed due to an issue in PostgreSQL installation. The reason for this issue is that PostgreSQL changes its GPG key when a new version is released. The same issue occurred a year ago, and the fix for that can be found in [1].
[1]: https://github.com/wso2/testgrid/pull/1489
**Goals**  
Install PostgreSQL without any errors.
**Approach**  
- Since we do not need the PostgreSQL server, we can install only the PostgreSQL client. This does not require GPG key verification.
- Revert ami changes- commit: 7ad326658164c3c6e957caa2222f02b213b35fdb
=> Fix postgres signature issue

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
=> Fix syntax issue in pg installation

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
Add isMigrated flag and a rocky AMI with docker for migration testing.
=> [APIM-Migration] Add Configurations for APIM Migration

jobs/intg-test-resources/update2-releases/wso2-u2-intg-test-cfn.yaml
**Purpose**
Remove deprecated PostgreSQL 15.3.
Add latest PostgreSQL 15.14
=> Upgrade PostgresSQL 15 version
